 SELECT PCCONTROI.CODROTINA
      ,PCCONTROI.CODUSUARIO
      ,PCCONTROI.CODCONTROLE
      ,PCCONTROI.ACESSO
      ,PCROTINAI.DESCRICAO NOMECONTROLE
FROM  PCCONTROI, PCROTINAI
WHERE 
--PCCONTROI.CODCONTROLE = '1'
--AND
 PCCONTROI.CODROTINA = '605'
 --AND  
  --PCCONTROI.CODUSUARIO = '17'
AND PCROTINAI.CODCONTROLE = PCCONTROI.CODCONTROLE
AND PCROTINAI.CODROTINA = PCCONTROI.CODROTINA
;

select * from PCCONTROI
where CODROTINA = '605';

--UPDATE PCCONTROI SET ACESSO = 'S' WHERE CODROTINA = '605' and CODCONTROLE ='4' and CODUSUARIO ='16'