SELECT CODEMITENTE, E.NOME,
NVL(MAX (DECODE (T, 'O', QTD, NULL)),0) "ORÇAMENTO",
NVL(MAX (DECODE (T, 'P', QTD, NULL)),0) "PEDIDO"
FROM (
   SELECT * FROM (
      SELECT 'P' T, CODEMITENTE, COUNT(0) QTD FROM PCPEDC GROUP BY CODEMITENTE
      UNION
      SELECT 'O' T, CODEMITENTE, COUNT(0) QTD FROM PCORCAVENDAC GROUP BY CODEMITENTE
   )
) DADOS, PCEMPR E
WHERE DADOS.CODEMITENTE = E.MATRICULA
GROUP BY CODEMITENTE, E.NOME
ORDER BY PEDIDO DESC
;