select 
  PCCLIENT.CODCLI,
   max(PCEMPR.NOME) as RCA,
   max(PCCLIENT.CLIENTE) as CLIENTE,
    PCATIVI.RAMO,
     PCCLIENT.TELENT as CELULAR,
      PCCLIENT.TELCOB as TELEFONE,
      PCCLIENT.MUNICCOB as MUNICIP,
       PCCLIENT.ESTCOB as  UF,
       to_char(PCCLIENT.LIMCRED - nvl((select SUM(nvl(P1.VALOR, 0)) - SUM(nvl(P1.VPAGO, 0))
from PCPREST P1
where P1.CODCLI = PCCLIENT.CODCLI
      and P1.DTPAG IS NULL
      and P1.CODCOB <> 'DESD'
      and P1.DTPAG IS NULL ), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as CRED_DISP,
  to_char(nvl(max(PCCLIENT.LIMCRED), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIMITE_CRED,
  nvl(max(PCCLIENT.DTULTCOMP), '31/12/9999') as ULTIMA_COMPRA,
  case
    when trunc((SYSDATE - nvl(max(PCCLIENT.DTULTCOMP), SYSDATE)) / 365) > 0 then
      trunc((SYSDATE - nvl(max(PCCLIENT.DTULTCOMP), SYSDATE)) / 365) || ' ANO(S) E ' || MOD(trunc(SYSDATE - nvl(max(PCCLIENT.DTULTCOMP), SYSDATE)), 365) || ' DIA(S) '
    else 
      trunc(SYSDATE - nvl(max(PCCLIENT.DTULTCOMP), SYSDATE)) || ' DIA(S)'
  end DIAS_SEM_COMPRA,
to_number(nvl((select 
    SUM(nvl(PCNFSAID.VLTOTAL, 0))
    from PCNFSAID
    where PCNFSAID.CODCLI = PCCLIENT.CODCLI
      and EXTRACT(MONTH from PCNFSAID.DTSAIDA) = EXTRACT(MONTH from ADD_MONTHS(SYSDATE, -1))
      and EXTRACT(YEAR from PCNFSAID.DTSAIDA) = EXTRACT(YEAR from ADD_MONTHS(SYSDATE, -1))
      and PCNFSAID.TIPOMOVGARANTIA is null
      and PCNFSAID.CONDVENDA in ('1','7')
  ), 0)) as MES_ANTERIOR,
to_number(nvl((select
    SUM(nvl(PCNFSAID.VLTOTAL, 0))
    from PCNFSAID
    where PCNFSAID.CODCLI = PCCLIENT.CODCLI
      and EXTRACT(MONTH from PCNFSAID.DTSAIDA) = EXTRACT(MONTH from SYSDATE)
      and EXTRACT(YEAR from PCNFSAID.DTSAIDA) = EXTRACT(YEAR from SYSDATE)
      and PCNFSAID.TIPOMOVGARANTIA is null
      and PCNFSAID.CONDVENDA in ('1','7')
  ), 0)) as MES_ATUAL,
to_number(nvl((select
    SUM(nvl(PCNFSAID.VLTOTAL, 0))
    from PCNFSAID
    where PCNFSAID.CODCLI = PCCLIENT.CODCLI
      and EXTRACT(YEAR from PCNFSAID.DTSAIDA) = EXTRACT(YEAR from SYSDATE)
      and PCNFSAID.TIPOMOVGARANTIA is null
      and PCNFSAID.CONDVENDA in ('1','7')
  ), 0)) as ANO_ATUAL,
to_number(nvl((select  
    SUM(nvl(PCNFSAID.VLTOTAL, 0))
    from PCNFSAID
    join PCCLIENT on PCNFSAID.CODCLI = PCCLIENT.CODCLI
    where 
    EXTRACT(YEAR from PCNFSAID.DTSAIDA) = EXTRACT(YEAR from ADD_MONTHS(SYSDATE, -11))
     and PCNFSAID.TIPOMOVGARANTIA is null
     and PCNFSAID.CONDVENDA in ('1','7')
  ), 0)) as ANO_ANTERIOR
from
  PCCLIENT
  left join PCEMPR on PCCLIENT.CODUSUR1 = PCEMPR.CODUSUR
  left join PCNFSAID on PCCLIENT.CODCLI = PCNFSAID.CODCLI
  join PCROTINA on PCEMPR.MATRICULA = PCEMPR.MATRICULA
  left join PCATIVI on PCNFSAID.CODATV1 = PCATIVI.CODATIV
where 
       PCEMPR.MATRICULA in (:MATRICULA) and
       PCNFSAID.CODATV1 in (:CODATV)    and
       PCROTINA.CODIGO = '8026'
  and (PCNFSAID.DTSAIDA is null or EXTRACT(YEAR from PCNFSAID.DTSAIDA) = EXTRACT(YEAR from SYSDATE))
group by
  PCCLIENT.CODCLI,
  PCCLIENT.LIMCRED,
  PCCLIENT.CODUSUR1,
  PCATIVI.RAMO,
  PCCLIENT.TELENT,
  PCCLIENT.TELCOB,
  PCCLIENT.MUNICCOB,
  PCCLIENT.ESTCOB
order by
  CRED_DISP desc,
  max(PCCLIENT.DTULTCOMP),
  PCCLIENT.CODCLI;