select * from
(
select EST.CODFILIAL FILIAL,
       PCTABPR.CODPROD,
       PCPRODUT.DESCRICAO,
       EST.QTESTGER - EST.QTRESERV - EST.QTBLOQUEADA DISPONÍVEL,
       round(((PCTABPR.PVENDA) - ((nvl(EST.CUSTOULTENT, 0) - 
                                   nvl(PCTRIBUT.PERDESCCUSTO, 0)) + (((PCTABPR.PVENDA) 
                                   * nvl(PCTRIBUT.CODICMTAB, 0)) / 100)  + ((PCTABPR.PVENDA) *
                                    nvl(PCPRODUT.PCOMREP1, 0)) / 100) + nvl(PCREGIAO.VLFRETEKG, 0)) / (PCTABPR.PVENDA) * 100, 2) MARGEM,
       PCREGIAO.REGIAO                             
from PCTABPR
join PCPRODUT on PCTABPR.CODPROD = PCPRODUT.CODPROD
join PCFORNEC on PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
join PCREGIAO on PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO
left join PCPRODFILIAL on PCTABPR.CODPROD = PCPRODFILIAL.CODPROD
join PCEST EST on PCPRODFILIAL.CODPROD = EST.CODPROD and PCPRODFILIAL.CODFILIAL = EST.CODFILIAL
join PCFILIAL on EST.CODFILIAL = PCFILIAL.CODIGO
join PCTABTRIB on PCTABPR.CODPROD = PCTABTRIB.CODPROD and PCTABTRIB.UFDESTINO = PCREGIAO.UF 
                  and PCTABTRIB.CODFILIALNF = DECODE(nvl(PCREGIAO.CODFILIAL,'99'), '99', EST.CODFILIAL, PCREGIAO.CODFILIAL)
join PCTRIBUT on PCTABTRIB.CODST = PCTRIBUT.CODST
where 0=0
      and ((PCREGIAO.STATUS not in ('I')) or (PCREGIAO.STATUS is null))
      and EST.CODFILIAL = '3'
      and PCTABPR.NUMREGIAO = '2'
      and PCPRODUT.DTEXCLUSAO is null
group by PCTABPR.CODPROD,
         PCTABPR.PVENDA,
         EST.CUSTOULTENT,
         PCTRIBUT.PERDESCCUSTO,
         PCTRIBUT.CODICMTAB,
         PCPRODUT.PCOMREP1,
         PCREGIAO.VLFRETEKG,
         PCPRODUT.DESCRICAO,
         PCREGIAO.REGIAO,
         EST.QTESTGER,
         EST.QTRESERV,
         EST.QTBLOQUEADA,
         EST.CODFILIAL
)
where 0=0
and MARGEM < 10
order by CODPROD;