--CUBO VENDAS PROTÓTIPO 5
 select 
  PCCLIENT.CODCLI,
    max(PCUSUARI.NOME) as RCA,
     max(PCCLIENT.CLIENTE) as CLIENTE,
      to_char(PCCLIENT.LIMCRED - nvl((
        select SUM(nvl(P1.VALOR, 0)) - SUM(nvl(P1.VPAGO, 0))
        from PCPREST P1
        where P1.CODCLI = PCCLIENT.CODCLI
        and P1.DTPAG is null
        and P1.CODCOB <> 'DESD'
        and P1.DTPAG is null
    ), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as CRED_DISP,
       to_char(max(PCCLIENT.LIMCRED), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIMITE_CRED,
         max(PCCLIENT.DTULTCOMP) as ULTIMA_COMPRA,
  case
  when
 trunc((SYSDATE - max(PCCLIENT.DTULTCOMP)) / 365) >0 
  then
  trunc((SYSDATE - max(PCCLIENT.DTULTCOMP)) / 365 )|| ' Ano(s) e ' || mod(trunc(SYSDATE - max(PCCLIENT.DTULTCOMP)), 365) || ' Dia(s) '
  else 
  trunc(SYSDATE - max(PCCLIENT.DTULTCOMP)) || ' Dia(s)'
  end DIAS_SEM_COMPRA,
 (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(MONTH from PCPEDC.DATA ) = extract(MONTH from add_MONTHS(SYSDATE, -1))
      and extract(YEAR from PCPEDC.DATA ) = extract(YEAR from add_MONTHS(SYSDATE, -1))
      and PCPEDC.POSICAO = 'F'
  ) as MES_ANTERIOR,
  (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(MONTH from PCPEDC.DATA) = extract(MONTH from SYSDATE)
      and extract(YEAR from PCPEDC.DATA) = extract(YEAR from SYSDATE)
      and PCPEDC.POSICAO = 'F'
  ) as MES_ATUAL,
  (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(YEAR from PCPEDC.DATA) = extract(YEAR from SYSDATE)
      and PCPEDC.POSICAO = 'F'
  ) as ANO_ATUAL,
  (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(YEAR from PCPEDC.DATA) = extract(YEAR from add_MONTHS (SYSDATE, -11))
      and PCPEDC.POSICAO = 'F'
  ) as ANO_ANTERIOR   
from
    PCCLIENT
    join PCPEDC on PCCLIENT.CODCLI = PCPEDC.CODCLI
    join PCUSUARI on PCPEDC.CODUSUR= PCUSUARI.CODUSUR
    join PCNFSAID on PCCLIENT.CODCLI = PCNFSAID.CODCLI
where
  PCPEDC.CODUSUR = '1011'
  and 
  extract(YEAR from PCPEDC.DATA) = extract(YEAR from SYSDATE)
group by
  PCCLIENT.CODCLI,
  PCCLIENT.LIMCRED
order by
  CRED_DISP desc,
  max(PCCLIENT.DTULTCOMP),
  PCCLIENT.CODCLI ; 
  
  
  


select
  PCCLIENT.CODCLI,
    max(PCUSUARI.NOME) as RCA,
     max(PCCLIENT.CLIENTE),
      to_char(max(PCCLIENT_BKPGL.LIMCRED), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIMITE_CRED,
        max(PCCLIENT.DTULTCOMP),
  floor(SYSDATE - max(PCCLIENT.DTULTCOMP))||' Dias' as Dias_Sem_compra,
  (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(MONTH from PCPEDC.DATA ) = extract(MONTH from add_MONTHS(SYSDATE, -1))
      and extract(YEAR from PCPEDC.DATA ) = extract(YEAR from add_MONTHS(SYSDATE, -1))
      and PCPEDC.POSICAO = 'F'
  ) as MES_ANTERIOR,
  (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(MONTH from PCPEDC.DATA) = extract(MONTH from SYSDATE)
      and extract(YEAR from PCPEDC.DATA) = extract(YEAR from SYSDATE)
      and PCPEDC.POSICAO = 'F'
  ) as MES_ATUAL,
  (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(YEAR from PCPEDC.DATA) = extract(YEAR from SYSDATE)
      and PCPEDC.POSICAO = 'F'
  ) as ANO_ATUAL,
  (
    select to_char(sum(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    from PCPEDC
    where PCPEDC.CODCLI = PCCLIENT.CODCLI
      and extract(YEAR from PCPEDC.DATA) = extract(YEAR from add_MONTHS (SYSDATE, -11))
      and PCPEDC.POSICAO = 'F'
  ) as ANO_ANTERIOR   

from
  PCPEDC
  join PCCLIENT on PCPEDC.CODCLI = PCPEDC.CODCLI
  join PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
  join PCCLIENT_BKPGL on PCPEDC.CODCLI = PCCLIENT_BKPGL.CODCLI
where
  PCPEDC.CODUSUR = '1011'
  and 
  extract(YEAR from PCPEDC.DATA) = extract(YEAR from SYSDATE)
group by
  PCCLIENT.CODCLI
order by
  max(PCCLIENT.DTULTCOMP)asc,
  PCCLIENT.CODCLI desc; 
  
  
  SELECT
  PCCLIENT.CODCLI,
  MAX(PCUSUARI.NOME) AS RCA,
  MAX(PCCLIENT.CLIENTE),
  TO_CHAR(MAX(PCCLIENT_BKPGL.LIMCRED), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS LIMITE_CRED,
  MAX(PCCLIENT.DTULTCOMP),
  CASE
    WHEN TRUNC((SYSDATE - MAX(PCCLIENT.DTULTCOMP)) / 365) > 0 THEN
      TRUNC((SYSDATE - MAX(PCCLIENT.DTULTCOMP)) / 365) || ' Ano(s) e ' || MOD(TRUNC(SYSDATE - MAX(PCCLIENT.DTULTCOMP)), 365) || ' Dia(s)'
    ELSE
      TRUNC(SYSDATE - MAX(PCCLIENT.DTULTCOMP)) || ' Dia(s)'
  END AS DIAS_SEM_COMPRA,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(MONTH FROM PCPEDC.DATA) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1))
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -1))
      AND PCPEDC.POSICAO = 'F'
  ) AS MES_ANTERIOR,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(MONTH FROM PCPEDC.DATA) = EXTRACT(MONTH FROM SYSDATE)
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM SYSDATE)
      AND PCPEDC.POSICAO = 'F'
  ) AS MES_ATUAL,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM SYSDATE)
      AND PCPEDC.POSICAO = 'F'
  ) AS ANO_ATUAL,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -11))
      AND PCPEDC.POSICAO = 'F'
  ) AS ANO_ANTERIOR
FROM
  PCPEDC
  JOIN PCCLIENT ON PCPEDC.CODCLI = PCCLIENT.CODCLI
  JOIN PCUSUARI ON PCPEDC.CODUSUR = PCUSUARI.CODUSUR
  JOIN PCCLIENT_BKPGL ON PCPEDC.CODCLI = PCCLIENT_BKPGL.CODCLI
WHERE
  PCPEDC.CODUSUR = '1011'
  AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY
  PCCLIENT.CODCLI
ORDER BY
  MAX(PCCLIENT.DTULTCOMP) ASC,
  PCCLIENT.CODCLI DESC;



----------------------------------
SELECT
  PCCLIENT.CODCLI,
  MAX(PCUSUARI.NOME) AS RCA,
  MAX(PCCLIENT.CLIENTE) AS CLIENTE,
  TO_CHAR (PCCLIENT_BKPGL.LIMCRED - max(PCNFSAID.VLTOTGER), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''' ) AS CRED_DISP,
  TO_CHAR(MAX(PCCLIENT_BKPGL.LIMCRED), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS LIMITE_CRED,
  MAX(PCCLIENT.DTULTCOMP) AS ULTIMA_COMPRA,
  CASE
    WHEN TRUNC((SYSDATE - MAX(PCCLIENT.DTULTCOMP)) / 365) > 0 THEN TRUNC((SYSDATE - MAX(PCCLIENT.DTULTCOMP)) / 365) || ' Ano(s) e ' || MOD(TRUNC(SYSDATE - MAX(PCCLIENT.DTULTCOMP)), 365) || ' Dia(s) '
    ELSE TRUNC(SYSDATE - MAX(PCCLIENT.DTULTCOMP)) || ' Dia(s)'
  END AS DIAS_SEM_COMPRA,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(MONTH FROM PCPEDC.DATA) = EXTRACT(MONTH FROM ADD_MONTHS(SYSDATE, -1))
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -1))
      AND PCPEDC.POSICAO = 'F'
  ) AS MES_ANTERIOR,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(MONTH FROM PCPEDC.DATA) = EXTRACT(MONTH FROM SYSDATE)
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM SYSDATE)
      AND PCPEDC.POSICAO = 'F'
  ) AS MES_ATUAL,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM SYSDATE)
      AND PCPEDC.POSICAO = 'F'
  ) AS ANO_ATUAL,
  (
    SELECT TO_CHAR(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')
    FROM PCPEDC
    WHERE PCPEDC.CODCLI = PCCLIENT.CODCLI
      AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM ADD_MONTHS(SYSDATE, -11))
      AND PCPEDC.POSICAO = 'F'
  ) AS ANO_ANTERIOR
FROM
  PCPEDC
  JOIN PCCLIENT ON PCPEDC.CODCLI = PCCLIENT.CODCLI
  JOIN PCUSUARI ON PCPEDC.CODUSUR = PCUSUARI.CODUSUR
  JOIN PCCLIENT_BKPGL ON PCPEDC.CODCLI = PCCLIENT_BKPGL.CODCLI
  JOIN PCNFSAID ON PCCLIENT.CODCLI = PCNFSAID.CODCLI
WHERE
   PCCLIENT_BKPGL.CODCLI = '7382'
  AND EXTRACT(YEAR FROM PCPEDC.DATA) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY
  PCCLIENT.CODCLI,
  PCCLIENT_BKPGL.LIMCRED
ORDER BY
  CRED_DISP,
  MAX(PCCLIENT.DTULTCOMP) ASC,
  PCCLIENT.CODCLI DESC;
