select ROUND((nvl(PCEST.QTESTGER, 0) - nvl(PCEST.QTRESERV, 0) - nvl(PCEST.QTBLOQUEADA, 0) - nvl(PCEST.QTPENDENTE, 0)) / NVL(PCEST.QTGIRODIA, 0), 2) EST_DIA
from PCEST join PCEMBALAGEM on PCEST.CODPROD = PCEMBALAGEM.CODPROD
where PCEST.CODPROD ='811' 
and PCEST.CODFILIAL = '4' fetch first 1 rows only ;