select (((PCEST.QTESTGER - PCEST.QTRESERV - PCEST.QTBLOQUEADA)/PCEMBALAGEM.QTUNIT) - PCEST.QTPENDENTE - PCEST.QTBLOQUEADA - PCEST.QTRESERV)/
       (( (NVL(PCEST.QTVENDMES, 0) QTVENDMES1) + (NVL(PCEST.QTVENDMES, 0) QTVENDMES2) + (NVL(PCEST.QTVENDMES, 0) QTVENDMES3)/ 90)  as QT 
from PCEST join PCEMBALAGEM on PCEST.CODPROD = PCEMBALAGEM.CODPROD
where PCEST.CODPROD ='811' 
and PCEST.CODFILIAL = '4' fetch first 1 rows only ;