--MARK1
select distinct
    PCPEDC.CODFILIAL as FILIAL,
     decode(PCPEDC.ORIGEMPED,'B', 'BALCÂO', 'R', 'RETIRA', 'T', 'ENTREGA') as ORIGEM,
      PCPEDC.DATA as DATA_PEDIDO,
       PCPEDC.NUMPED as PEDIDO,
        PCPEDC.NUMNOTA as NOTA,
         PCCLIENT.CLIENTE,
          PCPEDC.VLATEND as VALOR,
            PCPEDC.NUMCAR as CARREGAMENTO,
             PCVEICUL.DESCRICAO as VEICULO,
              PCEMPR.NOME as MOTORISTA,
               PCMANIFESTOELETRONICOC.NUMMDFE,
                decode(PCMANIFESTOELETRONICOC.SITUACAOMDFE,'101', 'CANCELADO', '102', 'ENCERRADO', '100', 'APROVADO') as STATUS_MDF,
                 case 
                 when PCPEDC.DTLIBERA is null 
                 then PCPEDC.DTFIMDIGITACAOPEDIDO
                else PCPEDC.DTLIBERA 
                end as DTLIBERAÇÃO,
                 PCNFSAID.DTHORAAUTORIZACAOSEFAZ as DT_FATURAMENTO, 
                   PCMANIFESTOELETRONICOC.DATAHORAGERACAO as DT_MDF,
                    PCNFSAID.DTCANHOTO as DT_CANHOTO
                     
from PCPEDC
left join PCCLIENT on PCPEDC.CODCLI = PCCLIENT.CODCLI
left join PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join PCEMPR on PCNFSAID.CODMOTORISTA = PCEMPR.MATRICULA
left join PCMANIFESTOELETRONICOI on PCNFSAID.NUMTRANSVENDA = PCMANIFESTOELETRONICOI.NUMTRANSVENDA
left join PCMANIFESTOELETRONICOC on PCMANIFESTOELETRONICOI.NUMMDFE = PCMANIFESTOELETRONICOC.NUMMDFE
left join PCCARREG on PCMANIFESTOELETRONICOC.CODMOTORISTA = PCCARREG.CODMOTORISTA
left join PCVEICUL on PCMANIFESTOELETRONICOC.CODVEICULO = PCVEICUL.CODVEICULO
where  
trunc(PCMANIFESTOELETRONICOC.DATAHORAGERACAO)
between 
'01/01/2023'
and 
'30/10/2023'
and 
PCMANIFESTOELETRONICOC.NUMMDFE in ('973');

;
select * from PCPEDC
where NUMCAR ='102';

select * from PCNFSAID
where NUMCAR = '102';


--PCNFSAID.DTCANHOTO


--MARK2 ( baseado para vizualizar carregamentos que estão sem MDF-e e canhoto)
select distinct
    PCPEDC.CODFILIAL as FILIAL,
     decode(PCPEDC.ORIGEMPED,'B', 'BALCÂO', 'R', 'RETIRA', 'T', 'ENTREGA') as ORIGEM,
      PCPEDC.DATA as DATA_PEDIDO,
       PCPEDC.NUMPED as PEDIDO,
        PCPEDC.NUMNOTA as NOTA,
         PCCLIENT.CLIENTE,
          PCCLIENT.MUNICENT,
           PCPRACA.PRACA, 
            PCPEDC.VLATEND as VALOR,
             PCPEDC.NUMCAR as CARREGAMENTO,
              PCVEICUL.DESCRICAO as VEICULO,
               PCEMPR.NOME as MOTORISTA,
                PCMANIFESTOELETRONICOC.NUMMDFE,
                decode(PCMANIFESTOELETRONICOC.SITUACAOMDFE,'101', 'CANCELADO', '102', 'ENCERRADO', '100', 'APROVADO') as STATUS_MDF,
                 case 
                 when PCPEDC.DTLIBERA is null 
                 then PCPEDC.DTFIMDIGITACAOPEDIDO
                 else PCPEDC.DTLIBERA 
                end as DTLIBERAÇÃO,
                 PCNFSAID.DTHORAAUTORIZACAOSEFAZ as DT_FATURAMENTO, 
                   PCMANIFESTOELETRONICOC.DATAHORAGERACAO as DT_MDF,
                    PCNFSAID.DTCANHOTO as DT_CANHOTO
                     
from PCPEDC
left join PCCLIENT on PCPEDC.CODCLI = PCCLIENT.CODCLI
left join PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join PCEMPR on PCNFSAID.CODMOTORISTA = PCEMPR.MATRICULA
left join PCMANIFESTOELETRONICOI on PCNFSAID.NUMTRANSVENDA = PCMANIFESTOELETRONICOI.NUMTRANSVENDA
left join PCMANIFESTOELETRONICOC on PCMANIFESTOELETRONICOI.NUMMDFE = PCMANIFESTOELETRONICOC.NUMMDFE
left join PCCARREG on PCMANIFESTOELETRONICOC.CODMOTORISTA = PCCARREG.CODMOTORISTA
left join PCVEICUL on PCMANIFESTOELETRONICOC.CODVEICULO = PCVEICUL.CODVEICULO
left join PCPRACA on PCCLIENT.CODPRACA = PCPRACA.CODPRACA
where  
trunc(PCPEDC.DATA)
between 
'01/01/2023'
and 
'10/07/2023'
and
PCMANIFESTOELETRONICOC.NUMMDFE is null
and 
PCNFSAID.DTCANHOTO is null
and
 PCMANIFESTOELETRONICOC.DATAHORAGERACAO is null
and
PCPEDC.ORIGEMPED = 'T'
and 
PCPEDC.POSICAO = 'F'
and 
PCNFSAID.DTCANCEL is null 
;