select PCCLIENT.CLIENTE, 
        PCPEDC.DATA || '  ' || PCPEDC.HORA || ':' || PCPEDC.MINUTO as PEDIDO,
         PCPEDC.DTINICIALSEP as EM_SEPARAÇÂO ,
          PCPEDC.DTFINALCHECKOUT as CONFERIDO,
           PCPEDC.DTLIBERA as PAGAMENTO,
            PCPEDC.DTFAT || ' ' || PCPEDC.HORAFAT || ':' || PCPEDC.MINUTOFAT as FATURADO,
             to_char(PCPEDC.HORAFAT, '00') || ':' || to_char(PCPEDC.MINUTOFAT, '00') as PRONTO_PARA_RETIRADA,
              PCNFSAID.DTCANHOTO as ENTREGUE  
from PCPEDC
join PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
join PCCLIENT on PCPEDC.CODCLI = PCCLIENT.CODCLI
where PCPEDC.DATA
between
'01/06/2023'
and
'01/07/2023'
and 
PCPEDC.CONDVENDA in ('1','8')
order by PCPEDC.DTINICIALSEP desc;