 SELECT PCCONTROI.CODROTINA
      ,PCCONTROI.CODUSUARIO
      ,PCCONTROI.CODCONTROLE
      ,PCCONTROI.ACESSO
      ,PCROTINAI.DESCRICAO NOMECONTROLE
FROM  PCCONTROI, PCROTINAI
WHERE 
--PCCONTROI.CODCONTROLE = '1'
--AND
 PCCONTROI.CODROTINA = '604'
 AND  
  PCCONTROI.CODUSUARIO = '17'
AND PCROTINAI.CODCONTROLE = PCCONTROI.CODCONTROLE
AND PCROTINAI.CODROTINA = PCCONTROI.CODROTINA
;

select * from PCCONTRO
where CODROTINA = '8038';

--UPDATE PCCONTRO SET ACESSO = 'S' WHERE CODROTINA = '8038'