WITH QTMASTER AS (
        SELECT   PCMOV.ROWID REGISTRO
               , DECODE(NVL(PCMOV.TIPOEMBALAGEMPEDIDO, 'V'), 'V', 1
                      , DECODE(NVL(PCPRODUT.QTUNITCX, 0), 0, 1, PCPRODUT.QTUNITCX)) QTUNITCX
            FROM PCMOV
               , PCPRODUT
           WHERE PCMOV.CODPROD = PCPRODUT.CODPROD
             AND PCMOV.NUMTRANSENT = '12855')
SELECT   PCMOV.ROWID
       , PCMOV.NUMTRANSENT
       , PCMOV.NUMPED
       , PCMOV.CODPROD
       , PCPRODUT.DESCRICAO
       , PCPRODUT.EMBALAGEM
       , PCPRODUT.UNIDADE
       , PCMOV.NUMSEQADICAO
       , PCMOV.NUMLOTE
       , PCMOV.NUMSEQ
       , PCMOV.NUMSEQPED
       , PCPRODUT.PESOVARIAVEL
       , PCMOV.CODCLI
       , PCMOV.CODFILIAL
       , PCMOV.PESOLIQ
       , PCMOV.PESOBRUTO
       , PCPRODUT.NBM NCM
       , PCMOV.NUMNEGOCIACAO       
       , NVL(PCNFENT.NUMTRANSORIGEM, PCNFENT.NUMTRANSENT) NUMTRANSORIGEM
       , NVL(PCPRODUT.CODPRODPRINC, PCPRODUT.CODPROD) CODPRODPRINC
       , DECODE(NVL(PCMOV.NUMADICAO, 0), 0, 1, PCMOV.NUMADICAO) NUMADICAO
       , (DECODE(NVL(PCMOV.QT,0), 0, PCMOV.QTCONT, PCMOV.QT) / QTMASTER.QTUNITCX) QT
       , (PCMOV.QTCONT / QTMASTER.QTUNITCX) QTCONT
       , (PCMOV.PUNIT * QTMASTER.QTUNITCX) PUNIT
       , (PCMOV.PTABELA * QTMASTER.QTUNITCX) PTABELA
       , (PCMOV.VLFRETE * QTMASTER.QTUNITCX) VLFRETE
       , (PCMOV.VLSEGURO * QTMASTER.QTUNITCX) VLSEGURO
       , (PCMOV.VLIPI * QTMASTER.QTUNITCX) VLIPI
       , (PCMOV.VLBASEIPI * QTMASTER.QTUNITCX) VLBASEIPI
       , (PCMOV.ST * QTMASTER.QTUNITCX) ST
       , (PCMOV.VLOUTRASDESP * QTMASTER.QTUNITCX) VLOUTRASDESP
       , (PCMOV.BASEICST * QTMASTER.QTUNITCX) BASEICST
       , (PCMOV.BASEICMS * QTMASTER.QTUNITCX) BASEICMS
       , (PCMOV.PLIQPED * QTMASTER.QTUNITCX) PLIQPED
       , (PCMOV.VLADICIONALBCST * QTMASTER.QTUNITCX) VLADICIONALBCST
       , (PCMOV.VLDESCICMSDIF * QTMASTER.QTUNITCX) VLDESCICMSDIF
       , (PCMOV.VLICMSDIFERIDO * QTMASTER.QTUNITCX) VLICMSDIFERIDO
       , (PCMOV.VLCREDPRESUMIDO * QTMASTER.QTUNITCX) VLCREDPRESUMIDO
       , (PCMOV.VLADUANEIRA * QTMASTER.QTUNITCX) VLADUANEIRA
       , (PCMOV.VLSISCOMEX * QTMASTER.QTUNITCX) VLSISCOMEX
       , (PCMOV.VLIMPORTACAO * QTMASTER.QTUNITCX) VLIMPORTACAO
       , (PCMOVCOMPLE.VLICMS * QTMASTER.QTUNITCX) VLICMS
       , (PCMOV.VLCREDICMS * QTMASTER.QTUNITCX) VLCREDICMS
       , (PCMOV.VLOUTRASDESPIMP * QTMASTER.QTUNITCX) VLOUTRASDESPIMP
       , (PCMOV.VLFRETEPORKG * QTMASTER.QTUNITCX) VLFRETEPORKG
       , (PCMOV.VALORDIREITOSADUANEIROS * QTMASTER.QTUNITCX) VALORDIREITOSADUANEIROS
       , (PCMOV.VALORIMPOSTOCONSUMO * QTMASTER.QTUNITCX) VALORIMPOSTOCONSUMO
       , (PCMOV.VALORIMPOSTOSELO * QTMASTER.QTUNITCX) VALORIMPOSTOSELO
       , (PCMOV.PAUTA * QTMASTER.QTUNITCX) PAUTA
       , (PCMOV.VLCREDPIS * QTMASTER.QTUNITCX) VLCREDPIS
       , (PCMOV.VLCREDCOFINS * QTMASTER.QTUNITCX) VLCREDCOFINS
       , (PCMOV.VLBASEPISCOFINS * QTMASTER.QTUNITCX) VLBASEPISCOFINS
       , (PCMOVCOMPLE.VLPAUTAPISCOFINS * QTMASTER.QTUNITCX) VLPAUTAPISCOFINS
       , (PCMOVCOMPLE.VLFRETENFCUSTO * QTMASTER.QTUNITCX) VLFRETENFCUSTO
       , (PCMOVCOMPLE.VLSEGUROCUSTO * QTMASTER.QTUNITCX) VLSEGUROCUSTO
       , (PCMOVCOMPLE.VLCAPATAZIACUSTO * QTMASTER.QTUNITCX) VLCAPATAZIACUSTO
       , (PCMOVCOMPLE.VLDESPDENTRONFCUSTO * QTMASTER.QTUNITCX) VLDESPDENTRONFCUSTO
       , (PCMOVCOMPLE.VLCAPATAZIA * QTMASTER.QTUNITCX) VLCAPATAZIA
       , (PCMOV.VLDESPDENTRONF * QTMASTER.QTUNITCX) VLDESPDENTRONF
       , (PCMOV.VLPAUTAICMS * QTMASTER.QTUNITCX) VLPAUTAICMS
       , (PCMOV.VLBASESTFORANF * QTMASTER.QTUNITCX) VLBASESTFORANF
       , (PCMOV.VLDESPADICIONAL * QTMASTER.QTUNITCX) VLDESPADICIONAL
       , (PCMOVCOMPLE.VLSISCOMEXCUSTO * QTMASTER.QTUNITCX) VLSISCOMEXCUSTO
       , (PCMOVCOMPLE.VLADUANEIRACUSTO * QTMASTER.QTUNITCX) VLADUANEIRACUSTO
       , (PCMOVCOMPLE.VLOUTRASDESPIMPCUSTO * QTMASTER.QTUNITCX) VLOUTRASDESPIMPCUSTO
       , (PCMOVCOMPLE.VLOUTROSCUSTOSCUSTO * QTMASTER.QTUNITCX) VLOUTROSCUSTOSCUSTO
       , (PCMOVCOMPLE.PTABELACUSTO * QTMASTER.QTUNITCX) PTABELACUSTO
       , (PCMOVCOMPLE.VLDESCONTOCUSTO * QTMASTER.QTUNITCX) VLDESCONTOCUSTO
       , (PCMOV.VLDESCONTO * QTMASTER.QTUNITCX) VLDESCONTO
       , (PCMOVCOMPLE.VLICMSANTECIPADO * QTMASTER.QTUNITCX) VLICMSANTECIPADO
       , (PCMOVCOMPLE.BASEICMSANTECIPADO * QTMASTER.QTUNITCX) BASEICMSANTECIPADO
       , (PCMOVCOMPLE.BASECREDPRESUMIDO * QTMASTER.QTUNITCX) BASECREDPRESUMIDO
       , (PCMOV.VLFRETECONHEC * QTMASTER.QTUNITCX) VLFRETECONHEC
       , (PCMOV.PUNITCONT * QTMASTER.QTUNITCX) PUNITCONT       
       , NVL(PCMOVCOMPLE.PERCSISCOMEXCUSTO, 0) PERCSISCOMEXCUSTO
       , NVL(PCMOVCOMPLE.PERCADUANEIRACUSTO, 0) PERCADUANEIRACUSTO
       , NVL(PCMOVCOMPLE.PERCOUTRASDESPIMPCUSTO, 0) PERCOUTRASDESPIMPCUSTO
       , NVL(PCMOVCOMPLE.PERCOUTROSCUSTOSCUSTO, 0) PERCOUTROSCUSTOSCUSTO
       , NVL(PCMOV.PERPIS, 0) PERPIS
       , NVL(PCMOV.PERCOFINS, 0) PERCOFINS
       , NVL(PCMOVCOMPLE.PERCCAPATAZIA, 0) PERCCAPATAZIA
       , NVL(PCMOV.PERICMGUIAPROPRIA, 0) PERICMGUIAPROPRIA
       , NVL(PCMOVCOMPLE.PERPISCALCDI, 0) PERPISCALCDI
       , NVL(PCMOVCOMPLE.PERCOFINSCALCDI, 0) PERCOFINSCALCDI
       , NVL(PCMOV.PERICMSANTECIPADO, 0) PERICMSANTECIPADO
       , NVL(PCMOV.PERCDESC, 0) PERCDESC
       , NVL(PCMOV.PERCFRETE, 0) PERCFRETE
       , NVL(PCMOV.PERCSEGURO, 0) PERCSEGURO
       , NVL(PCMOV.PERCIPI, 0) PERCIPI
       , NVL(PCMOV.PERCST, 0) PERCST
       , NVL(PCMOV.PERCOUTRASDESP, 0) PERCOUTRASDESP
       , NVL(PCMOV.PERCICM, 0) PERCICM
       , NVL(PCMOV.PERCICMRED, 0) PERCICMRED
       , NVL(PCMOV.PERCREDICMS, 0) PERCREDICMS
       , NVL(PCMOV.PERCFRETEFOB, 0) PERCFRETEFOB
       , NVL(PCMOV.PERCDESPFIN, 0) PERCDESPFIN
       , NVL(PCMOV.PERCDESCFIN, 0) PERCDESCFIN
       , NVL(PCMOV.PERCDESPADICIONAL, 0) PERCDESPADICIONAL
       , NVL(PCMOV.PERCIMPORTACAO, 0) PERCIMPORTACAO
       , NVL(PCMOV.ALIQICMS1, 0) ALIQICMS1
       , NVL(PCMOV.ALIQICMS2, 0) ALIQICMS2
       , NVL(PCMOV.PERCIVA, 0) PERCIVA
       , NVL(PCMOV.PERCCREDICMPRESUMIDO, 0) PERCCREDICMPRESUMIDO
       , NVL(PCMOV.PERCICMSDIFERIDO, 0) PERCICMSDIFERIDO
       , NVL(PCMOV.PERCIISUSPENSO, 0) PERCIISUSPENSO
       , NVL(PCMOV.PERCDESCICMSDIF, 0) PERCDESCICMSDIF
       , NVL(PCMOV.REDBASEIVA, 0) REDBASEIVA
       , NVL(PCMOV.REDBASEALIQEXT, 0) REDBASEALIQEXT
       , NVL(PCMOV.PERCOUTROSCUSTOS, 0) PERCOUTROSCUSTOS
       , NVL(PCMOVCOMPLE.VLOUTROSCUSTOS, 0) VLOUTROSCUSTOS
       , NVL(PCPRODUT.PERCALIQEXT, 0) PERCALIQEXT
       , NVL(PCMOV.PERCDIREITOSADUANEIROS, 0) PERCDIREITOSADUANEIROS
       , NVL(PCMOV.PERCIMPOSTOCONSUMO, 0) PERCIMPOSTOCONSUMO
       , NVL(PCMOV.PERCIMPOSTOSELO, 0) PERCIMPOSTOSELO
       , NVL(PCMOVCOMPLE.PERCFRETENFCUSTO, 0) PERCFRETENFCUSTO
       , NVL(PCMOVCOMPLE.PERCSEGUROCUSTO, 0) PERCSEGUROCUSTO
       , NVL(PCMOVCOMPLE.PERCCAPATAZIACUSTO, 0) PERCCAPATAZIACUSTO
       , NVL(PCMOVCOMPLE.PERCDESPDENTRONFCUSTO, 0) PERCDESPDENTRONFCUSTO
       , NVL(PCMOV.PERCICMSFRETEFOBST, 0) PERCICMSFRETEFOBST
       , PCPRODUT.TIPOMERC
       , PCPRODUT.UNIDADEMASTER
       , PCPRODUT.PRAZOMEDIOVENDA
       , PCMOV.SITTRIBUT
       , PCMOV.CODFISCAL
       , PCPRODUT.PROXNUMLOTE
       , PCPRODUT.PREFIXOLOTE
       , PCMOVCOMPLE.NUMDRAWBACK
       , PCPRODUT.CODFAB       
       , QTMASTER.QTUNITCX   
       , PCMOV.NUMBONO
       , PCMOV.CODEQUIPAMENTO           
       , NVL(PCPRODUT.TIPOESTOQUE, 'PA') TIPOESTOQUE       
       , NVL(PCMOVCOMPLE.USAPISCOFINSLIT, 'N') USAPISCOFINSLIT
       , NVL(PCMOV.APROVEITACREDICMS, 'N') APROVEITACREDICMS
       , NVL(PCMOV.APROVEITACREDPISCOFINS, 'N') APROVEITACREDPISCOFINS
       , NVL(PCMOV.GERAICMSLIVROFISCAL, 'S') GERAICMSLIVROFISCAL
       , NVL(PCMOV.PRODBONIFICADO, 'N') PRODBONIFICADO
       , NVL(PCMOV.CALCCREDIPI, NVL(PCPRODFILIAL.CALCCREDIPI, NVL(PCPRODUT.CALCCREDIPI, 'N'))) CALCCREDIPI
       , NVL(PCMOVCOMPLE.TIPOCALCST, 'N') TIPOCALCST
       , NVL(PCMOVCOMPLE.CALCTRIBMANUAL, 'N') CALCTRIBMANUAL
       , NVL(PCMOVCOMPLE.CODFILIALDEST, PCNFENT.CODFILIAL) CODFILIALDEST
       , DECODE(NVL(PCMOV.CODSITTRIBPISCOFINS, 0)
              , 0, PCPRODUT.CODSITTRIBPISCOFINS
              , PCMOV.CODSITTRIBPISCOFINS) CODSITTRIBPISCOFINS
       , NVL(PCPRODUT.ESTOQUEPORLOTE, 'N') ESTOQUEPORLOTE
       , NVL(PCPRODUT.CONTROLAVALIDADEDOLOTE, 'N') CONTROLAVALIDADEDOLOTE
       , NVL(PCPRODUT.VALIDARLOTE, 'N') VALIDARLOTE
       , NVL(PCMOVCOMPLE.IPIPORVALOR, 'N') IPIPORVALOR
       , NVL(PCMOVCOMPLE.PERCADUANEIRA, 0) PERCADUANEIRA
       , NVL(PCMOVCOMPLE.PERCSISCOMEX, 0) PERCSISCOMEX
       , NVL(PCMOVCOMPLE.UTILIZACREDREDPISCOFINS, 'N') UTILIZACREDREDPISCOFINS
       , NVL(PCMOV.PERCDESPDENTRONF, 0) PERCDESPDENTRONF
       , NVL(PCMOVCOMPLE.PERCOUTRASDESPIMP, 0) PERCOUTRASDESPIMP
       , NVL(PCMOV.PERCALIQEXTGUIA, 0) PERCALIQEXTGUIA
       , NVL(PCPRODFILIAL.CONSIDERASTNFCUSTO, 'S') CONSIDERASTNFCUSTO
       , NVL(PCPRODUT.LITRAGEM, 0) LITRAGEM
       , NVL(PCPRODFILIAL.TIPOARREDUNIDMASTER, 'N') TIPOARREDUNIDMASTER
       , NVL(PCPRODFILIAL.ACEITAVENDAFRACAO, 'N') ACEITAVENDAFRACAO
    FROM PCMOV
       , PCNFENT
       , PCFILIAL
       , PCCONSUM
       , PCMOVCOMPLE
       , PCPRODUT
       , PCDEPTO
       , PCPRODFILIAL
       , QTMASTER
   WHERE PCMOV.DTCANCEL IS NULL
     AND PCNFENT.CODCONT = PCNFENT.CODCONTFOR   
     AND PCNFENT.NUMTRANSENT = '12855'
     AND PCNFENT.CODFILIAL = PCFILIAL.CODIGO   
     AND PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
     AND PCMOV.NUMTRANSITEM = PCMOVCOMPLE.NUMTRANSITEM
     AND PCMOV.CODPROD = PCPRODUT.CODPROD
     AND PCMOV.CODPROD = PCPRODFILIAL.CODPROD
     AND PCMOV.CODFILIAL = PCPRODFILIAL.CODFILIAL
     AND PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
     AND PCMOV.CODFILIAL = PCPRODFILIAL.CODFILIAL
     AND PCMOV.ROWID = QTMASTER.REGISTRO     
ORDER BY PCMOV.NUMTRANSENT
       , PCMOV.CODPROD
