 
--MARK 1 ((sucesso) SEM AGC)
 select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
     to_char(SUM(PCNFSAID.VLDEVOLUCAO), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
      to_char(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
       to_char(SUM(PCPEDC.VLATEND) - coalesce (SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end,'9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
        to_char((SUM(PCPEDC.VLATEND) - coalesce (SUM(PCNFSAID.VLDEVOLUCAO),0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)* 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_0_5,
         to_char((SUM(PCPEDC.VLATEND) - coalesce (SUM(PCNFSAID.VLDEVOLUCAO),0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)* 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_0_25,
          to_char((SUM(PCPEDC.VLATEND) - coalesce (SUM(PCNFSAID.VLDEVOLUCAO),0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)* 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_0_25_2,
           to_char((((((((SUM(PCPEDC.VLATEND) - coalesce (SUM(PCNFSAID.VLDEVOLUCAO),0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)* 0.005)) + (((SUM(PCPEDC.VLATEND) - coalesce (SUM(PCNFSAID.VLDEVOLUCAO),0) - case when SUM(PCNFSAID.VLDEVOLUCAO)is null then 1 else 0 end) * 0.0025)) + ((SUM(PCPEDC.VLATEND) - coalesce (SUM(PCNFSAID.VLDEVOLUCAO),0) -  case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)  * 0.0025))))), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
  from
  PCPEDC
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
where
  PCPEDC.POSICAO = 'F'
and PCPEDC.DATA between 
 (:DTINI) 
and 
 (:DTFIM)
and (
 (:CODFILIAL is null)                     
or PCPEDC.CODFILIAL in (:CODFILIAL)       
     )
and (
 (:RCA is null)                           
OR PCPEDC.CODUSUR = (:RCA)                
     )
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME
order by
  PCPEDC.CODUSUR asc;


--MARK 2 (AGC N?O EST? SUBTRAINDO O LIQD, TORNANDO O VALOR COMISS?O FORA DO RESULTADO CORRETO)
select 
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(SUM(PCNFSAID.VLDEVOLUCAO), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL_DEVL,
  to_char(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL,
  to_char(SUM(COMISSAO_AGENCIADOR), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL_AGC,
  to_char(SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO), 0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS LIQD,
  to_char((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.005,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao,
  to_char((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao_margem,
  to_char((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao_meta,
  to_char(((((((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.005) + (
               (SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025) + (
               (SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025))))),'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao_TOTAL
from
  PCPEDC
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
where
  PCPEDC.POSICAO = 'F'
  and PCPEDC.DATA >= '01/05/2023'
  and PCPEDC.DATA <= '31/05/2023'
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME
order by
  PCPEDC.CODUSUR asc;



--MARK 3 ( melhorado com AGC SUBTRAINDO O LIQD, RESULTANDO NA COMISS?O EM SEU VALOR CORRETO)
select 
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(SUM(PCNFSAID.VLDEVOLUCAO), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL_AGC,
  to_char(SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end - coalesce(SUM(COMISSAO_AGENCIADOR), 0),'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.005,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char(((((((((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.005) + ((
                 (SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025) + ((
                 (SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025))))))))
                -- coalesce(sum(COMISSAO_AGENCIADOR), 0))
                  + case when sum(COMISSAO_AGENCIADOR) is null then 1 else 0 end),'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
where
  PCPEDC.POSICAO = 'F'
  and PCPEDC.DATA >= '01/05/2023'
  and PCPEDC.DATA <= '31/05/2023'
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME
order by
  PCPEDC.CODUSUR asc;


--MARK 4 (ajuste de valor do multiplicador de comiss?o para arredondamento com o sistema)
select 
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(SUM(PCNFSAID.VLDEVOLUCAO), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL_AGC,
  to_char(SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end - coalesce(SUM(COMISSAO_AGENCIADOR), 0),'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004874,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char(((((((((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004874) + ((
                 (SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025)))))))
                  + case when sum(COMISSAO_AGENCIADOR) is null then 1 else 0 end),'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char(((((((((SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004874) + ((
                 (SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025) + ((
                 (SUM(PCPEDC.VLATEND) - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.0025))))))))
                   -- coalesce(sum(COMISSAO_AGENCIADOR), 0))
                  + case when sum(COMISSAO_AGENCIADOR) is null then 1 else 0 end),'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
 -- join  
 -- PCNFENT on PCUSUARI.CODUSUR = PCNFENT.CODUSURDEVOL  
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
where
  PCPEDC.POSICAO = 'F'
--  and PCNFENT.CODDEVOL = '43'
  and PCPEDC.DATA >= '01/05/2023'
  and PCPEDC.DATA <= '31/05/2023'
  --and PCPEDC.CODUSUR='1003'
group by
  PCPEDC.CODUSUR
 ,PCUSUARI.NOME
order by
  PCPEDC.CODUSUR asc;



--relatorio 8024
select 
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(SUM(PCNFSAID.VLDEVOLUCAO), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL_DEVL,
  to_char(SUM(PCPEDC.VLATEND), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL,
  to_char(SUM(COMISSAO_AGENCIADOR), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TOTAL_AGC,
  to_char(SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO), 0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS LIQD,
  to_char((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.005,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao,
  to_char((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao_margem,
  to_char((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao_meta,
  to_char(((((((SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.005) + (
               (SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025) + (
               (SUM(PCPEDC.VLATEND) - COALESCE(SUM(PCNFSAID.VLDEVOLUCAO),0) - CASE WHEN SUM(PCNFSAID.VLDEVOLUCAO) IS NULL THEN 1 ELSE 0 END) * 0.0025))))),'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.''') AS comissao_TOTAL

--HEADER SUBSTITUIVEL (REVEJA OS PROTOTIPOS)
from
  PCPEDC
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
where
  PCPEDC.POSICAO = 'F'
and PCPEDC.DATA between 
 (:DTINI) 
and 
 (:DTFIM)
and (
 (:CODFILIAL is null)                     -- Se o campo CODFILIAL estiver vazio, retorna todos os resultados
or PCPEDC.CODFILIAL in (:CODFILIAL)       -- Caso contr?rio, filtra pelo valor do campo CODFILIAL
     )
and (
 (:RCA is null)                           -- Se o campo RCA estiver vazio, retorna todos os resultados
OR PCPEDC.CODUSUR = (:RCA)                -- Caso contr?rio, filtra pelo valor do campo RCA
     )
group by
  --PCPEDC.CODFILIAL,
  PCPEDC.CODUSUR,
  PCUSUARI.NOME
order by
  PCPEDC.CODUSUR asc;
--DML RELATORIO COMISS?O( ALTERA??O NA CODFILIAL E CODUSUR PARA TRAZER TODOS OS VALORES CASO N?O SE INFORME OS MESMOS)

  
--MARK 5 ( realiza?a? de calculo VLTOTAL de PCPEDC separadamente, para impedir que a inclus?o da tabela VW_COMISSAO_AGENCIADA interfira nos SUM's totais)
  select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(SUM(PCNFSAID.VLDEVOLUCAO), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)- coalesce(SUM(COMisSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004753, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004753) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376)
  )))) + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004756) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376)
  )))) + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVendA
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      SUM(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA >= '01/05/2023'
      and PCPEDC.DATA <= '31/05/2023'
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
  
where
  PCPEDC.POSICAO = 'F'
  and PCPEDC.DATA >= '01/05/2023'
  and PCPEDC.DATA <= '31/05/2023'
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND
order by
  PCPEDC.CODUSUR asc;

  


--relatorio 8024  (MARK 5)
select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(SUM(PCNFSAID.VLDEVOLUCAO), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)- coalesce(SUM(COMisSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004753, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004753) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376)
  )))) + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004756) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376)
  )))) + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
  
from
  PCPEDC
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      SUM(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and
      PCPEDC.DATA 
      between 
      (:DTINI)
	  and
	  (:DTFIM)
	  and (
      (:CODFILIAL is null)                     
      or PCPEDC.CODFILIAL in (:CODFILIAL)       
          )
      and (
      (:RCA is null)                           
      or PCPEDC.CODUSUR = (:RCA)                
          )
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
where
  PCPEDC.POSICAO = 'F'
and
 PCPEDC.DATA 
between 
 (:DTINI) 
and 
 (:DTFIM)
and (
 (:CODFILIAL is null)                     
or PCPEDC.CODFILIAL in (:CODFILIAL)       
     )
and (
 (:RCA is null)                           
or PCPEDC.CODUSUR = (:RCA)                
     )
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND
order by
  PCPEDC.CODUSUR asc;



--MARK 6
 select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(SUM(PCNFSAID.VLDEVOLUCAO) - (PCNFENT.VLTOTAL), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end)- coalesce(SUM(COMisSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004753, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004753) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376)
  )))) + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.004756) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376) + (
    (TOTAL_PCPEDC.VLATEND - coalesce(SUM(PCNFSAID.VLDEVOLUCAO), 0) + (PCNFENT.VLTOTAL) - case when SUM(PCNFSAID.VLDEVOLUCAO) is null then 1 else 0 end) * 0.002376)
  )))) + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      SUM(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA >= '01/05/2023'
      and PCPEDC.DATA <= '31/05/2023'
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
  join
  (
    select
      CODUSURDEVOL,
      sum(VLTOTAL) as VLTOTAL
    from
      PCNFENT
    where
      CODDEVOL = '43'
      and DTENT >= '01/05/2023'
      and DTENT <= '31/05/2023'
    group by
      CODUSURDEVOL
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
where
  PCPEDC.POSICAO = 'F'
  and PCPEDC.DATA >= '01/05/2023'
  and PCPEDC.DATA <= '31/05/2023'
  and PCPEDC.CODFILIAL in ('2','3','4')
 -- and PCPEDC.CODUSUR ='1011'
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL
order by
  PCPEDC.CODUSUR asc;
  
  
--MARK 7 (arredondamento de comiss?o/ devolu??o que deve debitar de TOTAL, ajustado) {ainda resta a adi??o do campo de margem e meta}
select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025))))
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025)))) 
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA
      between 
      '01/06/2023'
      and 
      '30/06/2023'
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
    select
      CODUSURDEVOL,
      sum(VLTOTAL) as VLTOTAL
    from
      PCNFENT
    where
      CODDEVOL <> '43'
      and DTENT
    between
      '01/06/2023'
      and 
      '30/06/2023'
    group by
      CODUSURDEVOL
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
    where
      PCPEDC.POSICAO = 'F'
     and PCPEDC.DATA
      between 
      '01/06/2023'
      and 
      '30/06/2023'

group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL
order by
  PCPEDC.CODUSUR asc;
  
  
  
--MARK 8 
select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(nvl(PCUSUARI.VLVENDAPREV,0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as META,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025))))
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025)))) 
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA
      between 
      '01/06/2023'
      and 
      '30/06/2023'
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
    select
      CODUSURDEVOL,
      sum(VLTOTAL) as VLTOTAL
    from
      PCNFENT
    where
      CODDEVOL <> '43'
      and DTENT
    between
      '01/06/2023'
      and 
      '30/06/2023'
    group by
      CODUSURDEVOL
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
    where
      PCPEDC.POSICAO = 'F'
     and PCPEDC.DATA
      between 
      '01/06/2023'
     and 
      '30/06/2023'
     and 
     PCNFSAID.TIPOMOVGARANTIA is null
     and
     PCNFSAID.CONDVENDA in ('1','7')
     
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL,
  PCUSUARI.VLVENDAPREV
order by
  PCPEDC.CODUSUR asc;


--MARK 9 (adi??o das condi??es em PCNFSAID para filtrar as condi??es de venda e processo de RMA)
select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(nvl(PCUSUARI.VLVENDAPREV,0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as META,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025))))
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025)))) 
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA
      between 
      '01/06/2023'
      and 
      '30/06/2023'
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
    select
      CODUSURDEVOL,
      sum(VLTOTAL) as VLTOTAL
    from
      PCNFENT
    where
      CODDEVOL <> '43'
      and DTENT
    between
      '01/06/2023'
      and 
      '30/06/2023'
    group by
      CODUSURDEVOL
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
    where
      PCPEDC.POSICAO = 'F'
     and PCPEDC.DATA
      between 
      '01/06/2023'
     and 
      '30/06/2023'
     and 
     PCNFSAID.TIPOMOVGARANTIA is null
     and
     PCNFSAID.CONDVENDA in ('1','7')
     
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL,
  PCUSUARI.VLVENDAPREV
order by
  PCPEDC.CODUSUR asc;


--MARK 10 (Rotina persinalizada para Vizualiza??o de Vendedores)
select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(nvl(PCUSUARI.VLVENDAPREV,0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as META,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao
from
  PCPEDC
left join PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join PCEMPR on PCUSUARI.CODUSUR = PCEMPR.CODUSUR
join PCROTINA on PCEMPR.MATRICULA  = PCEMPR.MATRICULA 
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA
      between ('01/06/2023') and ('30/06/2023')
      and PCPEDC.CODFILIAL = PCPEDC.CODFILIAL 
      and PCPEDC.CODUSUR = PCPEDC.CODUSUR
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
    select
      CODUSURDEVOL,
      sum(VLTOTAL) as VLTOTAL
    from
      PCNFENT
    join PCUSUARI on PCNFENT.CODUSURDEVOL = PCUSUARI.CODUSUR
    join PCEMPR on PCUSUARI.CODUSUR = PCEMPR.CODUSUR
    join PCROTINA on PCEMPR.MATRICULA  = PCEMPR.MATRICULA 
    where
      CODDEVOL <> '43'
      and DTENT
      between ('01/06/2023') and ('30/06/2023')
      and PCNFENT.CODFILIAL in ('2','3','4')
      and PCNFENT.CODUSURDEVOL = PCUSUARI.CODUSUR
      and PCEMPR.MATRICULA = '43'
      and PCROTINA.CODIGO = '8035'
    group by
      CODUSURDEVOL
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA
      between ('01/06/2023') and ('30/06/2023')
      and PCPEDC.CODFILIAL in ('2','3','4')
      and PCPEDC.CODUSUR = PCUSUARI.CODUSUR
      and PCEMPR.MATRICULA = '43'
      and PCROTINA.CODIGO = '8035'
      and PCNFSAID.TIPOMOVGARANTIA is null
      and PCNFSAID.CONDVENDA in ('1','7')
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL,
  PCUSUARI.VLVENDAPREV
order by
  PCPEDC.CODUSUR asc;


--  MARK 11 (Adi??o do campo de margem por vendedor, vale observar que essa subconsulta limita o resultado a apenas uma sele??o por vez) 
-- (vou tentar adicionar uma view dessa subconsulta para tentar eliminar o problema de limita??o de multipla sele??o. resumindo habilitar a sele??o multipla novamente)

select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(nvl(PCUSUARI.VLVENDAPREV,0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as META,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  ( select
    to_char((((sum(PCPEDI.PVENDA) over () - SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0))) over ()) / sum(PCPEDI.PVENDA) over ())* 100),'9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TESTE
from
    PCPRODUT,
    PCEST,
    PCPRODFILIAL,
    PCDEPTO,
    PCFORNEC,
    PCTABPR,
    PCTRIBUT,
    PCFILIAL,
    PCCONSUM,
    PCREGIAO,
    PCCOTACAOMOEDAI,
    PCTABTRIB,
    PCPEDC,
    PCPEDI,
    PCMOV
where
    PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
    and PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
    and PCEST.DTULTENT = PCCOTACAOMOEDAI.DATACOTACAO(+)
    --and PCCOTACAOMOEDAI.CODIGO(+) = :CODMOEDA
    and PCPRODUT.CODPROD = PCEST.CODPROD
    and PCPRODUT.CODPROD = PCTABPR.CODPROD
    -- and PCTABPR.NUMREGIAO = DECODE(nvl(2,-1),-1, nvl(PCFILIAL.NUMREGIAOPADRAO, PCCONSUM.NUMREGIAOPADRAO), 2)
    and PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO
    and PCEST.CODFILIAL = PCPRODFILIAL.CODFILIAL
    and PCEST.CODPROD = PCPRODFILIAL.CODPROD
    and PCEST.CODFILIAL = PCPEDC.CODFILIAL
    and PCFILIAL.CODIGO = PCEST.CODFILIAL
    and PCPRODUT.CODPROD = PCPEDI.CODPROD
    and PCTABTRIB.CODFILIALNF in ('2','3','4')
    and PCTABTRIB.UFDESTINO = PCREGIAO.UF
    and PCTABTRIB.CODPROD = PCTABPR.CODPROD
    and PCTABTRIB.CODST = PCTRIBUT.CODST
  --  and PCPEDC.NUMPED = '1032000755'
    and PCMOV.QT = PCPEDI.QT
    and PCMOV.PUNIT = PCPEDI.PVENDA
    and PCPEDC.CODUSUR in ('1011')
    and PCPEDC.DATA between '01/07/2023' and '31/07/2023'
    and PCPEDI.NUMPED = PCPEDC.NUMPED
    -- and PCPEDI.CODPROD = '893'
    and PCTABPR.NUMREGIAO = PCPEDC.NUMREGIAO
group by
    PCTABPR.PVENDA,
    PCPEDI.PVENDA,
    PCEST.CUSTOULTENT,
    PCTRIBUT.PERDESCCUSTO,
    PCREGIAO.VLFRETEKG,
    PCPRODUT.PCOMREP1,
    PCTRIBUT.CODICMTAB,
    PCPEDI.CODPROD,
    PCREGIAO.NUMREGIAO,
    PCMOV.QT,
    PCMOV.PUNIT,
    PCPEDC.NUMPED
order by
    PCPEDI.PVENDA
    fetch first 1 rows only
    ) as MARGEM,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025))))
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025)))) 
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join
  PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join
  VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join
  PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DATA
      between 
      '01/07/2023'
     and
      '31/07/2023'
      and 
      PCPEDC.CODFILIAL = PCPEDC.CODFILIAL 
      and 
      PCPEDC.CODUSUR = PCPEDC.CODUSUR
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
    select
      CODUSURDEVOL,
      sum(VLTOTAL) as VLTOTAL
    from
      PCNFENT
    where
      CODDEVOL <> '43'
      and DTENT
    between
      '01/07/2023'
     and
      '31/07/2023'
     and 
      PCNFENT.CODFILIAL in ('2','3','4')
     and 
      PCNFENT.CODUSURDEVOL in ('1011')
    group by
      CODUSURDEVOL
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
    where
      PCPEDC.POSICAO = 'F'
     and PCPEDC.DATA
      between 
      '01/07/2023'
     and
      '31/07/2023'
      and 
      PCPEDC.CODFILIAL in ('2','3','4')
      and 
      PCPEDC.CODUSUR in ('1011')
      and 
      PCNFSAID.TIPOMOVGARANTIA is null
      and
      PCNFSAID.CONDVENDA in ('1','7')
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL,
  PCUSUARI.VLVENDAPREV
order by
  PCPEDC.CODUSUR asc;
  
  --MARK 12 ( adição do campo de margem com o calculo correto, adendo da subtração dos valores respectivos e CUSTO,FATURAMENTO e Receita para caso haja devoluções)
  
  select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(nvl(PCUSUARI.VLVENDAPREV,0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as META,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  (select 
    to_char((sum(S.FATURAMENTO - S.CUSTO) / sum(S.FATURAMENTO)) * 100,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.') as MARG 
from  (
    select
        F.CODUSUR,
        sum((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT)) as CUSTO,
        sum((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT)) as FATURAMENTO,
        sum((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT)
        - (F.CUSTOULTENT * F.QT) - (((F.PERCOM/100) * F.PUNIT) * F.QT) - (((F.CODICMTAB/100) * F.PUNIT) * F.QT)) as REC
    from
        PCMOV F
        left join PCCLIENT C on C.CODCLI = F.CODCLI
        left join PCUSUARI S on S.CODUSUR = F.CODUSUR
    where
        F.CODOPER in ('S')
        and F.CODFISCAL not in (5117, 6117)
        and F.DTCANCEL is null
        and (F.CODDEVOL not in (43) or F.CODDEVOL is null)
        and F.CODUSUR in ('1039')
        and F.CODFILIAL in ('2','3','4')
        and F.DTMOV between ('01/08/2023') and ('17/08/2023')
    group by
        F.CODUSUR

    union all

    select
        F.CODUSUR,
        sum(-((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT))) as CUSTO,
        sum(-((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT))) as FATURAMENTO,
        sum(-((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT))
        - ((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT))) as REC
    from
        PCMOV F
        left join PCCLIENT C on C.CODCLI = F.CODCLI
        left join PCUSUARI S on S.CODUSUR = F.CODUSUR
    where
        F.CODOPER in ('ED')
        and F.CODFISCAL not in (5117, 6117)
        and F.DTCANCEL is null
        and (F.CODDEVOL not in (43) or F.CODDEVOL is null)
        and F.CODUSUR in ('1039')
        and F.CODFILIAL in ('2','3','4')
        and F.DTMOV between ('01/08/2023') and ('17/08/2023')
    group by
        F.CODUSUR
) S
group by
    S.CODUSUR) as MARGEM,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025))))
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025)))) 
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DTFAT
      between '01/08/2023' and '17/08/2023'
      and PCPEDC.CODFILIAL = PCPEDC.CODFILIAL 
      and PCPEDC.CODUSUR = PCPEDC.CODUSUR
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
    select
      CODUSURDEVOL,
      sum(VLTOTAL) as VLTOTAL
    from
      PCNFENT
    where
      CODDEVOL <> '43'
     and DTENT
     between ('01/08/2023') and ('17/08/2023')
     and  PCNFENT.CODFILIAL in ('2','3','4')
     and PCNFENT.CODUSURDEVOL in ('1039')
    group by
      CODUSURDEVOL
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
    where
      PCPEDC.POSICAO = 'F'
     and PCPEDC.DTFAT
      between  '01/08/2023' and '17/08/2023'
      and  PCPEDC.CODFILIAL in ('2','3','4')
      and  PCPEDC.CODUSUR in ('1039')
      and  PCNFSAID.TIPOMOVGARANTIA is null
      and  PCNFSAID.CONDVENDA in ('1','7')
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL,
  PCUSUARI.VLVENDAPREV
order by
  PCPEDC.CODUSUR asc;
  
--MARK 13

select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(nvl(PCUSUARI.VLVENDAPREV,0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as META,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  (select 
    to_char((sum(S.FATURAMENTO - S.CUSTO) / sum(S.FATURAMENTO)) * 100,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.') as MARG 
from  (
    select
        F.CODUSUR,
        sum((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT)) as CUSTO,
        sum((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT)) as FATURAMENTO,
        sum((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT)
        - (F.CUSTOULTENT * F.QT) - (((F.PERCOM/100) * F.PUNIT) * F.QT) - (((F.CODICMTAB/100) * F.PUNIT) * F.QT)) as REC
    from
        PCMOV F
        left join PCCLIENT C on C.CODCLI = F.CODCLI
        left join PCUSUARI S on S.CODUSUR = F.CODUSUR
    where
        F.CODOPER in ('S')
        and F.CODFISCAL not in (5117, 6117)
        and F.DTCANCEL is null
        and (F.CODDEVOL not in (43) or F.CODDEVOL is null)
        and F.CODUSUR in ('1039')
        and F.CODFILIAL in ('2','3','4')
        and F.DTMOV between ('01/08/2023') and ('17/08/2023')
    group by
        F.CODUSUR

    union all

    select
        F.CODUSUR,
        sum(-((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT))) as CUSTO,
        sum(-((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT))) as FATURAMENTO,
        sum(-((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT))
        - ((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT))) as REC
    from
        PCMOV F
        left join PCCLIENT C on C.CODCLI = F.CODCLI
        left join PCUSUARI S on S.CODUSUR = F.CODUSUR
    where
        F.CODOPER in ('ED')
        and F.CODFISCAL not in (5117, 6117)
        and F.DTCANCEL is null
        and (F.CODDEVOL not in (43) or F.CODDEVOL is null)
        and F.CODUSUR in ('1039')
        and F.CODFILIAL in ('2','3','4')
        and F.DTMOV between ('01/08/2023') and ('17/08/2023')
    group by
        F.CODUSUR
) S
group by
    S.CODUSUR) as MARGEM,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025))))
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_margem_meta,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_meta,
  to_char((((((((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025) + 
    (TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.0025)))) 
     + case when SUM(COMISSAO_AGENCIADOR) is null then 1 else 0 end, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao_TOTAL
from
  PCPEDC
left join PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DTFAT
      between '01/08/2023' and '17/08/2023'
      and PCPEDC.CODFILIAL = PCPEDC.CODFILIAL 
      and PCPEDC.CODUSUR = PCPEDC.CODUSUR
    group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
select 
      PCNFENT.CODUSURDEVOL,
      sum(PCNFENT.VLTOTAL) as VLTOTAL
from 
    PCNFENT
left join PCESTCOM on PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT
left join PCTABDEV on PCNFENT.CODDEVOL = PCTABDEV.CODDEVOL
left join PCCLIENT on PCNFENT.CODFORNEC = PCCLIENT.CODCLI
left join PCEMPR on PCNFENT.CODMOTORisTADEVOL = PCEMPR.MATRICULA
left join PCUSUARI on PCNFENT.CODUSURDEVOL = PCUSUARI.CODUSUR
left join PCSUPERV on PCUSUARI.CODSUPERVisOR = PCSUPERV.CODSUPERVisOR
left join PCEMPR FUNC on PCNFENT.CODFUNCLANC = FUNC.MATRICULA
left join PCNFSAID on PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
left join PCDEVCONSUM on PCNFENT.NUMTRANSENT = PCDEVCONSUM.NUMTRANSENT
where  
      PCNFENT.DTENT between '01/08/2023' and '17/08/2023'
      and PCNFENT.TIPODESCARGA in ('6','7','T') 
      and nvl(PCNFENT.OBS, 'X') <> 'NF CANCELADA'
      and PCNFENT.CODFisCAL in ('131','132','231','232','199','299') 
      and ((nvl(PCNFSAID.ConDVENDA, 0) in ('1', '7') and PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA)
         or (PCNFENT.VLTOTGER is null and PCNFENT.CODUSURDEVOL = '1039'))
      and PCNFENT.CODDEVOL in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,47,52,55)
      and PCNFENT.CODUSURDEVOL in ('1039') 
group by 
PCNFENT.CODUSURDEVOL                     
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
    where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DTFAT
      between ('01/08/2023') and ('17/08/2023')
      and PCPEDC.CODFILIAL in ('2','3','4')
      and PCPEDC.CODUSUR in ('1039')
      and PCNFSAID.TIPOMOVGARANTIA is null
      and PCNFSAID.CONDVENDA in ('1','7')
group by
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  TOTAL_PCPEDC.VLATEND,
  PCNFENT.VLTOTAL,
  PCUSUARI.VLVENDAPREV
order by
  PCPEDC.CODUSUR asc;
  
  --MARK 14 (atualização da MARK 10 para vendedores com base na MARK 13)
  select
  PCPEDC.CODUSUR,
  PCUSUARI.NOME,
  to_char(nvl(PCUSUARI.VLVENDAPREV,0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as META,
  to_char(PCNFENT.VLTOTAL, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_DEVL,
  to_char(TOTAL_PCPEDC.VLATEND, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL,
  (select to_char((sum(S.FATURAMENTO - S.CUSTO) / sum(S.FATURAMENTO)) * 100,'9G999G999G999D99','NLS_NUMERIC_CHARACTERS = '',.') as MARG 
    from  
       ( 
        select
        F.CODUSUR,
        sum((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT)) as CUSTO,
        sum((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT)) as FATURAMENTO,
        sum((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT)
        - (F.CUSTOULTENT * F.QT) - (((F.PERCOM/100) * F.PUNIT) * F.QT) - (((F.CODICMTAB/100) * F.PUNIT) * F.QT)) as REC
        from
            PCMOV F
          left join PCCLIENT C on C.CODCLI = F.CODCLI
          left join PCUSUARI S on S.CODUSUR = F.CODUSUR
          left join PCEMPR   P on S.CODUSUR = P.CODUSUR
          left join PCROTINA R on PCEMPR.MATRICULA = PCEMPR.MATRICULA 
            where
            F.CODOPER in ('S')
            and F.CODFISCAL not in (5117, 6117)
            and F.DTCANCEL is null
            and (F.CODDEVOL not in (43) or F.CODDEVOL is null)
            and F.CODUSUR = S.CODUSUR
            and P.MATRICULA = 35
            and R.CODIGO = '8035'
            and F.CODFILIAL in ('2','3','4')
            and F.DTMOV between ('01/08/2023') and ('31/08/2023')
            group by
            F.CODUSUR

union all

select
       F.CODUSUR,
       sum(-((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT))) as CUSTO,
       sum(-((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT))) as FATURAMENTO,
       sum(-((F.PUNIT * F.QT) + (nvl(F.VLFRETE, 0) * F.QT) + (nvl(F.VLOUTROS, 0) * F.QT))
       - ((F.CUSTOULTENT * F.QT) + (((F.PERCOM/100) * F.PUNIT) * F.QT) + (((F.CODICMTAB/100) * F.PUNIT) * F.QT))) as REC
       from
        PCMOV F
      left join PCCLIENT C on C.CODCLI = F.CODCLI
      left join PCUSUARI S on S.CODUSUR = F.CODUSUR
      left join PCEMPR   P on S.CODUSUR = P.CODUSUR
      left join PCROTINA R on PCEMPR.MATRICULA  = PCEMPR.MATRICULA 
        where
        F.CODOPER in ('ED')
        and F.CODFISCAL not in (5117, 6117)
        and F.DTCANCEL is null
        and (F.CODDEVOL not in (43) or F.CODDEVOL is null)
        and F.CODUSUR = S.CODUSUR
        and P.MATRICULA = 35
        and R.CODIGO = '8035'
        and F.CODFILIAL in ('2','3','4')
        and F.DTMOV between ('01/08/2023') and ('31/08/2023')
        group by
        F.CODUSUR
) S
group by
    S.CODUSUR) as MARGEM,
  to_char(coalesce(SUM(COMISSAO_AGENCIADOR), 0), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as TOTAL_AGC,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as LIQD,
  to_char((TOTAL_PCPEDC.VLATEND  - coalesce (PCNFENT.VLTOTAL,0) - coalesce(SUM(COMISSAO_AGENCIADOR), 0)) * 0.005, '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as comissao
from
  PCPEDC
left join PCNFSAID on PCPEDC.NUMPED = PCNFSAID.NUMPED
left join VW_COMISSAO_AGENCIADA on PCPEDC.NUMTRANSVENDA = VW_COMISSAO_AGENCIADA.NUMTRANSVENDA
join PCUSUARI on PCPEDC.CODUSUR = PCUSUARI.CODUSUR
join PCEMPR on PCUSUARI.CODUSUR = PCEMPR.CODUSUR
join PCROTINA on PCEMPR.MATRICULA  = PCEMPR.MATRICULA 
join
  (
    select
      PCPEDC.CODUSUR,
      sum(PCPEDC.VLATEND) as VLATEND
    from
      PCPEDC
      where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DTFAT between ('01/08/2023') and ('31/08/2023')
      and PCPEDC.CODFILIAL = PCPEDC.CODFILIAL 
      and PCPEDC.CODUSUR = PCPEDC.CODUSUR
      group by
      PCPEDC.CODUSUR
  ) TOTAL_PCPEDC on PCPEDC.CODUSUR = TOTAL_PCPEDC.CODUSUR
left join
  (
    select 
      PCNFENT.CODUSURDEVOL,
      sum(PCNFENT.VLTOTAL) as VLTOTAL
      from 
    PCNFENT
  left join PCESTCOM on PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT
  left join PCTABDEV on PCNFENT.CODDEVOL = PCTABDEV.CODDEVOL
  left join PCCLIENT on PCNFENT.CODFORNEC = PCCLIENT.CODCLI
  left join PCEMPR FUNC on PCNFENT.CODFUNCLANC = FUNC.MATRICULA
  left join PCNFSAID on PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
  left join PCDEVCONSUM on PCNFENT.NUMTRANSENT = PCDEVCONSUM.NUMTRANSENT
  left join PCUSUARI S on S.CODUSUR = PCNFENT.CODUSURDEVOL
  left join PCEMPR   P on S.CODUSUR = P.CODUSUR
  left join PCROTINA R on P.MATRICULA  = P.MATRICULA 
    where  0=0
    and PCNFENT.DTENT between ('01/08/2023') and ('31/08/2023')
    and PCNFENT.TIPODESCARGA in ('6','7','T') 
    and nvl(PCNFENT.OBS, 'X') <> 'NF CANCELADA'
    and PCNFENT.CODFISCAL in ('131','132','231','232','199','299') 
    and ((nvl(PCNFSAID.CONDVENDA, 0) in ('1', '7') and PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA)
         or (PCNFENT.VLTOTGER is null and PCNFENT.CODUSURDEVOL = S.CODUSUR))
    and PCNFENT.CODDEVOL in (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,47,52,55)
    and PCNFENT.CODUSURDEVOL = S.CODUSUR
    and P.MATRICULA = 35
    and R.CODIGO = '8035'
    and PCNFENT.CODFILIALNF in ('2','3','4')
    group by 
    PCNFENT.CODUSURDEVOL                     
  ) PCNFENT on PCPEDC.CODUSUR = PCNFENT.CODUSURDEVOL
      where
      PCPEDC.POSICAO = 'F'
      and PCPEDC.DTFAT
      between ('01/08/2023') and ('31/08/2023')
      and PCPEDC.CODFILIAL in ('2','3','4')
      and PCPEDC.CODUSUR = PCUSUARI.CODUSUR
      and PCEMPR.MATRICULA = 35
      and PCROTINA.CODIGO = '8035'
      and PCNFSAID.TIPOMOVGARANTIA is null
      and PCNFSAID.CONDVENDA in ('1','7')
      group by
      PCPEDC.CODUSUR,
      PCUSUARI.NOME,
      TOTAL_PCPEDC.VLATEND,
      PCNFENT.VLTOTAL,
      PCUSUARI.VLVENDAPREV
order by
PCPEDC.CODUSUR asc;