select distinct PCNFSAID.NUMNOTA as NOTA, 
                 VW_COMISSAO_AGENCIADA.CODCONTATO,
                  VW_COMISSAO_AGENCIADA.NOMECONTATO as AGC,
                   PCNFSAID.CODUSUR as RCA, 
                    PCUSUARI.NOME,
                     PCNFSAID.CODCLI,
                      PCCLIENT.CLIENTE,
                       PCNFSAID.VLTOTAL,
                        VW_COMISSAO_AGENCIADA.COMISSAO_AGENCIADOR as COMISSAO,
                        case 
                        when PCPEDC.CODCONTATO is null
                        then PCNFSAID.NUMNOTA, PCNFSAID.CODUSUR as RCA, PCUSUARI.NOME, PCNFSAID.CODCLI, PCCLIENT.CLIENTE, PCNFSAID.VLTOTAL 
                        end NDA
from PCNFSAID
left join VW_COMISSAO_AGENCIADA on PCNFSAID.NUMNOTA = VW_COMISSAO_AGENCIADA.NUMNOTA
left join PCPEDC on PCNFSAID.NUMNOTA = PCPEDC.NUMNOTA
left join PCCLIENT on PCNFSAID.CODCLI = PCCLIENT.CODCLI
left join PCUSUARI on PCNFSAID.CODUSUR = PCUSUARI.CODUSUR
where 
PCNFSAID.DTSAIDA
between
'01/05/2023'
and 
'31/07/2023'
and 
PCNFSAID.CODFILIALNF in ('2','3','4')
and 
PCNFSAID.NUMNOTA = '15270'
and  
PCNFSAID.CODUSUR in  ('1065')
and
VW_COMISSAO_AGENCIADA.CODCONTATO in (select CODCONTATO from PCCONTATO where CARGO in ('5089') )  

  

---

select distinct
    case
        when VW_COMISSAO_AGENCIADA.CODCONTATO is null then PCNFSAID.NUMNOTA
        else PCNFSAID.NUMNOTA
    end AS NOTA,
    VW_COMISSAO_AGENCIADA.CODCONTATO,
    VW_COMISSAO_AGENCIADA.NOMECONTATO as AGC,
    case
        when VW_COMISSAO_AGENCIADA.CODCONTATO is null then PCNFSAID.CODUSUR
        else PCNFSAID.CODUSUR
    end as RCA,
    case
        when VW_COMISSAO_AGENCIADA.CODCONTATO is null then PCUSUARI.NOME
        else PCUSUARI.NOME
    end NOME,
    case
        when VW_COMISSAO_AGENCIADA.CODCONTATO is null then PCNFSAID.CODCLI
        else PCNFSAID.CODCLI
    end CODCLI,
    case
        when VW_COMISSAO_AGENCIADA.CODCONTATO is null then PCCLIENT.CLIENTE
        else PCCLIENT.CLIENTE
    end as CLIENTE,
    case
        when VW_COMISSAO_AGENCIADA.CODCONTATO is null then PCNFSAID.VLTOTAL
        else PCNFSAID.VLTOTAL
    end as VLTOTAL,
    VW_COMISSAO_AGENCIADA.COMISSAO_AGENCIADOR as COMISSAO
from PCNFSAID
left join VW_COMISSAO_AGENCIADA on PCNFSAID.NUMNOTA = VW_COMISSAO_AGENCIADA.NUMNOTA
left join PCPEDC on PCNFSAID.NUMNOTA = PCPEDC.NUMNOTA
left join PCCLIENT on PCNFSAID.CODCLI = PCCLIENT.CODCLI
left join PCUSUARI on PCNFSAID.CODUSUR = PCUSUARI.CODUSUR
where 
PCNFSAID.DTSAIDA
between
'01/05/2023'
and 
'31/07/2023'
and 
PCNFSAID.CODFILIALNF in ('2','3','4')
--and 
--PCNFSAID.NUMNOTA = '15270'
