select distinct E1.CODFILIAL, E1.CODPROD, P.CODFAB, P.DESCRICAO, A.MARCA, E1.CUSTOULTENT as CUSTO_FILIAL_2,
       E2.CUSTOULTENT as CUSTO_FILIAL_3
from PCEST E1
join PCPRODUT P on E1.CODPROD = P.CODPROD
join PCEST E2 on E1.CODPROD = E2.CODPROD and E2.CODFILIAL = '3'
join PCMOV M on E1.CODPROD = M.CODPROD and M.CODFILIAL = '3'
join PCMARCA A on P.CODMARCA = A.CODMARCA
where E1.CODFILIAL = '2' and E1.CUSTOULTENT <> E2.CUSTOULTENT
and E1.CUSTOULTENT <> '0'
and M.CODOPER = 'ET';

