select PCPRODUT.MODULO, 
       PCPRODUT.RUA, 
       PCPRODUT.NUMERO, 
       PCPRODUT.APTO,
       PCPRODUT.CODPROD,
       PCPRODUT.DV,
       PCPRODUT.DESCRICAO,
       PCPRODUT.CODAUXILIAR,
       PCPRODUT.CODFAB, 
       PCPRODUT.EMBALAGEM, 
       PCPRODUT.PONTOREPOSICAO,
       PCPRODUT.PONTOREPOSICAOCX,
       PCPRODUT.LASTROPAL,
       PCPRODUT.ALTURAPAL,
       PCPRODUT.QTTOTPAL,
       PCPRODUT.CAPACIDADEPICKING,
       PCPRODUT.UNIDADE,
       CASE 
         WHEN E.CODFILIAL = 2
         THEN PCPRODUT.DESCRICAO2
         WHEN E.CODFILIAL = 3 
         THEN PCPRODUT.DESCRICAO3
         WHEN E.CODFILIAL = 4 
         THEN PCPRODUT.DESCRICAO4
         ELSE PCPRODUT.DESCRICAO1
END ENDERECO
       
from   PCPRODUT
JOIN PCEST E ON PCPRODUT.CODPROD = E.CODPROD
where 1 = 1
 and PCPRODUT.CODPROD = '804' 
 and E.CODFILIAL ='2'
 order by PCPRODUT.CODPROD