SELECT PCRATEIOCENTROCUSTO.CODIGOCENTROCUSTO CODCENTROCUSTO
       , RECNUM
       , DESCRICAO
       , CODCONTA
       , PERCRATEIO
       , VALOR
    FROM PCRATEIOCENTROCUSTO
       , PCCENTROCUSTO
   WHERE PCRATEIOCENTROCUSTO.CODIGOCENTROCUSTO = PCCENTROCUSTO.CODIGOCENTROCUSTO
     AND RECNUM = '9549'
ORDER BY CODCENTROCUSTO


-------------
select count(*) 
from PCRATEIOCENTROCUSTO
join PCCENTROCUSTO on PCRATEIOCENTROCUSTO.CODIGOCENTROCUSTO = PCCENTROCUSTO.CODIGOCENTROCUSTO
join PCLANC on PCRATEIOCENTROCUSTO.RECNUM = PCLANC.RECNUM
where PCLANC.NUMTRANS = '218'
-- group by PCCENTROCUSTO.DESCRICAO;
;


select PCCENTROCUSTO.DESCRICAO
    from PCRATEIOCENTROCUSTO
       , PCCENTROCUSTO
       ,PCLANC
   where PCRATEIOCENTROCUSTO.CODIGOCENTROCUSTO = PCCENTROCUSTO.CODIGOCENTROCUSTO
     and PCRATEIOCENTROCUSTO.RECNUM = PCLANC.RECNUM
     and PCLANC.NUMTRANS = '218';
      --fetch first 1 rows only
      
      
select 
 case
      when (SELECT COALESCE(CAST(COUNT(*) AS VARCHAR(10)), '0') AS COUNT_RESULT FROM  PCRATEIOCENTROCUSTO JOIN PCCENTROCUSTO ON PCRATEIOCENTROCUSTO.CODIGOCENTROCUSTO = PCCENTROCUSTO.CODIGOCENTROCUSTO JOIN  PCLANC ON PCRATEIOCENTROCUSTO.RECNUM = PCLANC.RECNUM WHERE PCLANC.NUMTRANS = '218')  
      = '0' then 'ND/a'
      else PCCENTROCUSTO.DESCRICAO
      end CENTRO_CUSTO 
from PCRATEIOCENTROCUSTO
join PCCENTROCUSTO on PCRATEIOCENTROCUSTO.CODIGOCENTROCUSTO = PCCENTROCUSTO.CODIGOCENTROCUSTO
join PCLANC on PCRATEIOCENTROCUSTO.RECNUM = PCLANC.RECNUM
where PCLANC.NUMTRANS = '218'
group by PCCENTROCUSTO.DESCRICAO;



from PCRATEIOCENTROCUSTO join PCCENTROCUSTO on PCRATEIOCENTROCUSTO.CODIGOCENTROCUSTO = PCCENTROCUSTO.CODIGOCENTROCUSTO join PCLANC on PCRATEIOCENTROCUSTO.RECNUM = PCLANC.RECNUM where PCLANC.NUMTRANS is null;



