SELECT
  (((PCCOB.TXJUROS / 100) / 30) * PCPREST.VALOR * ATRASO + (PCCOB.PERCMULTA / 100) * PCPREST.VALOR) - PCPREST.VALORDESC AS RESULTADO
FROM
  (
    SELECT
      PCPREST.*,
      CASE
        WHEN ((PCPREST.DTPAG IS NULL)
          OR (PCPREST.DTPAG IS NOT NULL AND ((PCPREST.CODCOB = 'PERD') OR (PCPREST.CODCOB = 'CANO')))
          AND (PCPREST.DTVENC < TRUNC(SYSDATE))) THEN TRUNC(SYSDATE) - PCPREST.DTVENC
        WHEN (PCPREST.DTPAG IS NOT NULL) AND (PCPREST.DTVENC < PCPREST.DTPAG) THEN PCPREST.DTPAG - PCPREST.DTVENC
        ELSE 0
      END AS ATRASO
    FROM
      PCPREST 
      JOIN PCCOB ON PCPREST.CODCOB = PCCOB.CODCOB
    WHERE
      PCPREST.DTEMISSAO BETWEEN TO_DATE('27/12/2022', 'DD/MM/YYYY') AND TO_DATE('21/02/2023', 'DD/MM/YYYY')
      AND PCPREST.CODFILIAL IN ('2', '3', '4', '50', '96', '97', '98', '99')
      AND PCPREST.NUMTRANSVENDA = 168021
      AND PCPREST.PREST = 2
      AND ((TRUNC(SYSDATE) - PCPREST.DTVENC) >= 1)
  ) PCPREST
  JOIN PCCOB ON PCPREST.CODCOB = PCCOB.CODCOB
ORDER BY PCPREST.DTVENC, PCPREST.CODCLI;
