select  
    M.CODFILIAL as FILIAL,
    M.DTMOV AS DTSAID,
    M.NUMNOTA AS NOTA_SAID,
    M.CODOPER,
    M.CODPROD,
    T.DESCRICAO,
    M.QT,
    M.CODFISCAL as CFOP,
    M.CODCLI,
    C.CLIENTE,
    (S.VLPIS * M.QT) as VLPIS_SAID,
    (S.VLCOFINS * M.QT) as VLCOFINS_SAID, 
    M.BASEICMS as BASEICM_SAID,
    ((M.BASEICMS * (M.PERCICM /100)) * M.QT) as VLICMS_SAID,
    (M.VLBASEIPI * M.QT) as BASEIPI_SAID,
    (M.VLIPI * M.QT) as VLIPI_SAID,
     A.CHAVENFE as CHAVENFE
    
from VW_MANUT_NF_SAID S
join PCMOV M on S.NUMNOTA = M.NUMNOTA and S.CODPROD = M.CODPROD and S.CODFILIAL = M.CODFILIAL
join PCNFSAID A on S.NUMNOTA = A.NUMNOTA and S.NUMTRANSVENDA = A.NUMTRANSVENDA 
join PCCLIENT C on M.CODCLI = C.CODCLI
join PCPRODUT T on M.CODPROD = T.CODPROD
where 0=0
and M.DTMOV between '01/02/2023' and '23/09/2023'
and M.CODFILIAL in ('4')
and M.NUMNOTA = '15269'
and M.DTCANCEL is null
and M.STATUS <> 'B'
and A.ESPECIE = 'NF'
and A.DTCANCEL is null
order by CODCLI;


select * from VW_MANUT_NF_SAID order by NUMNOTA asc;


select * from PCNFSAID where NUMNOTA ='15269'