
 select 
    PCNFENT.CODFILIALNF as FILIAL,
    PCNFENT.NUMNOTA as NOTA_ENT, 
    PCNFENT.CODFISCAL as CFOP_ENT,
    PCNFENT.CODFUNCLANC as FUNCLANC,
    FUNC.NOME NOMEFUNCLANC,
    PCNFENT.DTENT,
    PCNFENT.CODUSURDEVOL as RCA,
    PCUSUARI.NOME as NOME_RCA,
    PCCLIENT.CODCLI,
    nvl(PCDEVCONSUM.CLIENTE, PCCLIENT.CLIENTE) CLIENTE,
    PCNFSAID.CONDVENDA as TIPO_VEND,
    PCNFENT.DTSAIDA,
    PCNFSAID.NUMNOTA as NOTA_SAID
 --   decode(PCNFENT.VLTOTAL, 0, PCESTCOM.VLDEVOLUCAO, PCNFENT.VLTOTAL) as VLTOTAL,
 --   case 
 --       when PCNFENT.VLTOTGER is null 
 -- 		then 'CREDITO AO CLIENTE NÃO GERADO'
 --       else to_char(PCNFENT.VLTOTGER)
 --   end as CREDITO_CLI
from PCNFENT, 
     PCESTCOM, 
     PCTABDEV,
     PCCLIENT,
     PCEMPR,
     PCUSUARI, 
     PCSUPERV,
     PCEMPR FUNC,
     PCNFSAID,
     PCDEVCONSUM
where  ( PCNFENT.CODDEVOL = PCTABDEV.CODDEVOL(+) )
and    PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT (+)
and   ( PCNFENT.CODFORNEC  = PCCLIENT.CODCLI )
and   ( PCNFENT.NUMTRANSENT = PCDEVCONSUM.NUMTRANSENT(+) )
 and    nvl(PCNFENT.CODFILIALNF, PCNFENT.CODFILIAL) = '2'
and   ( PCNFENT.CODFUNCLANC       = FUNC.MATRICULA(+))
and   ( PCNFENT.CODMOTORISTADEVOL = PCEMPR.MATRICULA(+))
and   (  PCNFENT.CODUSURDEVOL  = PCUSUARI.CODUSUR )
and   ( PCUSUARI.CODSUPERVISOR    = PCSUPERV.CODSUPERVISOR(+))
-- and   ( PCNFENT.DTENT between '01/05/2023' and '23/08/2023' )
and   ( PCNFENT.TIPODESCARGA in ('6','7','T') ) 
and   ( nvl(PCNFENT.OBS, 'X') <> 'NF CANCELADA')
and   ( PCNFENT.CODFISCAL in ('131','132','231','232','199','299') )
and exists (select PCPRODUT.CODPROD from PCPRODUT, PCMOV
             WHERE PCMOV.CODPROD = PCPRODUT.CODPROD
             and PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
             and PCMOV.NUMNOTA = PCNFENT.NUMNOTA
             and PCMOV.DTCANCEL is null
 and nvl(PCNFENT.CODFILIALNF, PCNFENT.CODFILIAL) = '2'
-- and   ( PCNFENT.DTENT BETWEEN '01/05/2023' AND '23/08/2023' ) 
             and PCMOV.CODFILIAL = PCNFENT.CODFILIAL)
and nvl(PCNFSAID.CONDVENDA,0) not in (4, 8, 10, 13, 20, 98, 99)
and PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA 
group by 
    PCNFENT.NUMNOTA,
    PCNFENT.CODFUNCLANC,
    PCNFENT.DTENT,
    PCNFENT.DTSAIDA,                                           
    PCNFENT.CODDEVOL,
    PCNFENT.OBS,
    PCTABDEV.MOTIVO,
    PCNFENT.NUMTRANSENT,                                            
    nvl(PCNFENT.TOTPESO, 0),
    PCNFENT.CODFILIALNF,
    PCCLIENT.CODCLI,                                                 
    nvl(PCDEVCONSUM.CLIENTE, PCCLIENT.CLIENTE) ,
    nvl(PCDEVCONSUM.CIDADE, PCCLIENT.MUNICENT),                        
    nvl(PCDEVCONSUM.ENDERECO, PCCLIENT.ENDERENT),
    nvl(PCDEVCONSUM.TELEFONE, PCCLIENT.TELENT),                       
    PCNFENT.CODUSURDEVOL,
    PCNFENT.ROTINALANC,
    PCNFENT.CODMOTORISTADEVOL,                                            
    PCEMPR.NOME,
    PCUSUARI.NOME,
    PCUSUARI.CODSUPERVISOR,
    PCSUPERV.NOME,
    FUNC.NOME,
    PCNFENT.CODFILIAL,
    PCNFENT.VLFRETE, 
    PCNFENT.VLOUTRAS,
    PCNFENT.VLTOTAL,
    PCESTCOM.VLDEVOLUCAO,
    PCNFENT.CODFORNEC,
    PCNFSAID.NUMCAR,
    PCNFENT.VLTOTGER,
    PCNFENT.CODFISCAL,
    PCNFSAID.NUMNOTA,
    PCNFSAID.CODFISCAL,
    PCNFSAID.CONDVENDA
order by 
    PCNFENT.NUMNOTA;
    
--consulta de devolucao avulsa
select PCMOV.CODFILIAL,
    PCMOV.DTMOV AS DTENT,
    max(PCMOV.NUMNOTA) AS NOTA_ENT,
    PCMOV.CODOPER,
    PCMOV.CODFISCAL,
    PCMOV.CODCLI,
    C.CLIENTE
from PCMOV
left join PCCLIENT C on PCMOV.CODCLI = C.CODCLI
where DTMOV between '01/05/2023' and '23/08/2023'
and NUMPED = '0'
and CODFILIAL = '2'
and CODOPER = 'ED'
and DTCANCEL is null
and NUMNOTADEV is not null
group by
    PCMOV.CODFILIAL,
    PCMOV.DTMOV,
    PCMOV.CODOPER,
    PCMOV.CODFISCAL,
    PCMOV.CODCLI,
    PCMOV.NUMNOTADEV,
    C.CLIENTE;

--consulta de CFOP devol avulsa  
    select 
    M.CODFILIAL,
    M.DTMOV AS DTENT,
    M.NUMNOTA AS NOTA_ENT,
    M.CODOPER,
    M.CODPROD,
    T.DESCRICAO,
    M.CODFISCAL,
    M.CODCLI,
    C.CLIENTE
from PCMOV M
join PCCLIENT C on M.CODCLI = C.CODCLI
join PCPRODUT T on M.CODPROD = T.CODPROD
join VW_DEVOL_AVUL D on M.NUMNOTA = D.NOTA_ENT
where D.DTENT between '01/05/2023' and '23/08/2023'
and M.CODFILIAL ='2'
and M.CODOPER = 'ED'
order by M.NUMNOTA
;

select * from PCMOV
where NUMNOTA = '3427';

---quase (perfect)

select 
    M.CODFILIAL,
    M.DTMOV as DTENT,
    M.NUMNOTA as NOTA_ENT,
    null as NOTA_SAID,
    M.CODOPER,
    M.CODPROD,
    T.DESCRICAO,
    M.CODFISCAL,
    M.CODCLI,
    C.CLIENTE,
    null as CFOP_SAID,
    null as TIPO,
    null as VENDA
from PCMOV M
join PCCLIENT C on M.CODCLI = C.CODCLI
join PCPRODUT T on M.CODPROD = T.CODPROD
join VW_DEVOL_AVUL D on M.NUMNOTA = D.NOTA_ENT and M.CODFILIAL = D.FILIAL
where D.DTENT between '01/05/2023' and '23/08/2023'
and M.CODFILIAL in('2')
and M.CODOPER = 'ED'

union all

select 
    M.CODFILIAL,
    M.DTMOV as DTENT,
    M.NUMNOTA as NOTA_ENT,
    P.NUMNOTA as NOTA_SAID,
    M.CODOPER,
    M.CODPROD,
    T.DESCRICAO,
    M.CODFISCAL,
    M.CODCLI,
    C.CLIENTE,
    I.CODFISCAL as CFOP_SAID,
    P.CONDVENDA as TIPO,
    decode(nvl(P.CONDVENDA, 0),0, 'NDA',1, 'VENDA NORMAL',5, 'BONIFICACAO',7, 'NOTA MÃE',8, 'NOTA FILHA',9, 'DEMONSTRAÇÃO',10, 'TRANSFERÊNCIA') as VENDA
from PCMOV M
join PCCLIENT C on M.CODCLI = C.CODCLI
join PCPRODUT T on M.CODPROD = T.CODPROD
join VW_DEVOL_VENDA D on M.NUMNOTA = D.NOTA_ENT and M.CODFILIAL = D.FILIAL
join PCPEDC P on D.NOTA_SAID = P.NUMNOTA
join PCPEDI I on P.NUMPED = I.NUMPED and M.CODPROD = I.CODPROD
where D.DTENT between '01/05/2023' and '23/08/2023'
and M.CODFILIAL in ('2')
and M.CODOPER = 'ED'
order by NOTA_ENT; 
