select * from VW_COMISSAO_AGENCIADA_TRY WHERE NUMNOTA = 91351 ;

SELECT * FROM PCLANC WHERE HISTORICO LIKE '%91351%';

SELECT 
       P.RECNUM,
       P.CODFILIAL,
       W.DTSAIDA,
       W.DTVENC,
       W.NUMNOTA,  --P.NUMNOTA (NUMNOTA EM PCLANC É ALEATORIO PARA COMISSÃO ATUALMENTE, PODENDO ASSIM USA-LÁ PARA O INSERT)
       W.NUMTRANSVENDA,
       P.CODCONTA,
       P.HISTORICO, --INFORMAR O CAMPO W.COBRANCA (COMO VARIAVEL AUTOMATICO INICIAL NO HISTORICO)
       P.CODFORNECPRINC,
       P.FORNECEDOR,
       P.VALOR,
       P.PARCELA,
       C.CODIGOCENTROCUSTO,
       P.PRCRATEIOUTILIZADO,
       U.DESCRICAO
       
       FROM PCLANC P,
        PCRATEIOCENTROCUSTO C, 
        PCCENTROCUSTO U, 
       VW_COMISSAO_AGENCIADA_TRY W 
       WHERE P.HISTORICO = '91351' 
       AND W.NUMNOTA = '91351' and W.DTVENC = '13/12/2023'
       AND C.RECNUM = P.RECNUM
       AND U.CODIGOCENTROCUSTO = C.CODIGOCENTROCUSTO
       ORDER BY P.RECNUM ;
       
SELECT * FROM VW_COMISSAO_AGENCIADA_TRY WHERE NUMNOTA = '91351';


SELECT * FROM PCLANC WHERE HISTORICO LIKE '91351' ORDER BY RECNUM