
SELECT RECNUM TRANSACAO,
       CODFILIAL,
       DTVENC,
       DTPAGTO DTPAG,
       DTPAGTOMES,
       DTPAGTOANO,
       CODCLI,
       CLIENTE,
       SUM(NVL(VPAGO,0)) VLTOTAL,
       CMV,
       CODCONTA,
       CONTA
FROM ( 
SELECT  PCLANC.RECNUM, 
        PCLANC.DTVENC,
        PCLANC.DTPAGTO, 
        to_char((PCLANC.DTVENC),'MM') DTPAGTOMES,
        to_char((PCLANC.DTVENC),'YYYY') DTPAGTOANO,
        (DECODE(PCLANC.DTPAGTO, NULL, PCLANC.VALOR, (DECODE(nvl(PCLANC.VPAGO,0),0,DECODE(PCLANC.DESCONTOFIN, PCLANC.VALOR, PCLANC.VALOR, DECODE(PCLANC.VALORDEV, PCLANC.VALOR, PCLANC.VALOR, 0)),nvl(PCLANC.VPAGO,0) + NVL(PCLANC.VALORDEV,0)) * (1)))) * (-1) VPAGO,
         DECODE(PCLANC.TIPOPARCEIRO,
         'F', (SELECT CODFORNEC FROM PCFORNEC WHERE CODFORNEC = PCLANC.CODFORNEC), 
         'R', (SELECT CODUSUR FROM PCUSUARI WHERE CODUSUR = PCLANC.CODFORNEC), 
         'M', (SELECT MATRICULA FROM PCEMPR WHERE MATRICULA = PCLANC.CODFORNEC), 
         'L', (SELECT MATRICULA FROM PCEMPR WHERE MATRICULA = PCLANC.CODFORNEC), 
         'C', (SELECT CODCLI FROM PCCLIENT WHERE CODCLI = PCLANC.CODFORNEC), 
         '0') AS  CODCLI,
         DECODE(PCLANC.TIPOPARCEIRO,
         'F', (SELECT FORNECEDOR FROM PCFORNEC WHERE CODFORNEC = PCLANC.CODFORNEC), 
         'R', (SELECT NOME FROM PCUSUARI WHERE CODUSUR = PCLANC.CODFORNEC), 
         'M', (SELECT NOME FROM PCEMPR WHERE MATRICULA = PCLANC.CODFORNEC), 
         'L', (SELECT NOME FROM PCEMPR WHERE MATRICULA = PCLANC.CODFORNEC), 
         'C', (SELECT CLIENTE FROM PCCLIENT WHERE CODCLI = PCLANC.CODFORNEC), 
         'OUTROS') AS  CLIENTE,
         PCLANC.CODFILIAL,
         PCLANC.CODCONTA,
         PCCONTA.CONTA,
         null CMV
FROM PCLANC,
     PCNFSAID,
     PCCONSUM,
     PCCONTA
WHERE 0=0
AND PCLANC.CODCONTA = PCCONTA.CODCONTA
and PCCONTA.GRUPOCONTA IN ('201','202','250','301','302','303','304','305','306','307','401','402','403','404','405','406','501')
AND (NVL(PCCONTA.INVESTIMENTO,'N') <> 'S')
AND NVL(PCLANC.CODROTINABAIXA,0) <> 737
AND (SELECT COUNT(C.NUMSEQCONTRATOEMPRESTIMO) 
     FROM PCCONTRATOEMPRESTIMO C, PCLANC LC 
     WHERE C.NUMSEQCONTRATOEMPRESTIMO = LC.NUMSEQCONTRATOEMPRESTIMO 
       AND C.TIPOCONTRATO = 6 
       AND NVL(LC.CODROTINABAIXA,0) = 772 
       AND LC.RECNUM = PCLANC.RECNUM) = 0 
AND PCLANC.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+)
 AND NVL (PCNFSAID.CONDVENDA, 0) NOT IN (10, 20, 98, 99) 
 AND (    ( NVL(PCNFSAID.CODFISCAL,0) NOT IN (522,622,722,532,632,732) )
       OR ( TO_CHAR(PCLANC.CODCONTA) = (SELECT VALOR FROM PCPARAMFILIAL WHERE NOME = 'CON_CODCONTRECJUR') )
     )
       AND (SELECT COUNT(D.NUMTRANSENT) 
              FROM PCESTCOM D, PCNFSAID N 
            WHERE D.NUMTRANSENT = PCLANC.NUMTRANSENT 
              AND D.DTESTORNO = PCLANC.DTLANC 
              AND D.NUMTRANSVENDA = N.NUMTRANSVENDA 
              AND N.CONDVENDA IN (20)) = 0 
   AND  ( --realizados                 
     (  (PCLANC.DTPAGTO IS NOT NULL)   
   AND  (PCLANC.DTPAGTO >= '01/04/2024' ) 
   AND  (PCLANC.DTPAGTO <= '30/04/2024' )    
   AND  NVL(PCLANC.VPAGO,0) <> 0
     )                                 
        OR --previstos                 
     (  (PCLANC.DTPAGTO IS NULL)       
   AND  (PCLANC.DTVENC >= '01/04/2024' )  
   AND  (PCLANC.DTVENC <= '30/04/2024' )     
   AND  NVL(PCLANC.VALOR,0) <> 0       
     ) )                               
UNION 
SELECT BA.RECNUM 
      ,BA.DTVENC
      ,BA.DTPAGTO 
      ,to_char((BA.DTVENC),'MM') DTPAGTOMES
      ,to_char((BA.DTVENC),'YYYY') DTPAGTOANO
      ,BA.VPAGO + NVL(BA.VLVARIACAOCAMBIAL, 0) AS VPAGO 
      ,DECODE(BA.TIPOPARCEIRO 
             ,'F',(SELECT CODFORNEC FROM PCFORNEC WHERE CODFORNEC = BA.CODFORNEC) 
             ,'R',(SELECT CODUSUR FROM PCUSUARI WHERE CODUSUR = BA.CODFORNEC) 
             ,'M',(SELECT MATRICULA FROM PCEMPR WHERE MATRICULA = BA.CODFORNEC) 
             ,'L',(SELECT MATRICULA FROM PCEMPR WHERE MATRICULA = BA.CODFORNEC) 
             ,'C',(SELECT CODCLI FROM PCCLIENT WHERE CODCLI = BA.CODFORNEC) 
             ,'0') AS CODCLI 
      ,DECODE(BA.TIPOPARCEIRO 
             ,'F',(SELECT FORNECEDOR FROM PCFORNEC WHERE CODFORNEC = BA.CODFORNEC) 
             ,'R',(SELECT NOME FROM PCUSUARI WHERE CODUSUR = BA.CODFORNEC) 
             ,'M',(SELECT NOME FROM PCEMPR WHERE MATRICULA = BA.CODFORNEC) 
             ,'L',(SELECT NOME FROM PCEMPR WHERE MATRICULA = BA.CODFORNEC) 
             ,'C',(SELECT CLIENTE FROM PCCLIENT WHERE CODCLI = BA.CODFORNEC) 
             ,'OUTROS') AS CLIENTE 
      ,BA.CODFILIAL 
      ,BA.CODCONTA
      ,PCCONTA.CONTA
      ,null CMV
  FROM PCLANCADIANTFORNEC A 
      ,PCLANC LA --LANCAMENTO DO ADIANTAMENTO 
      ,PCLANC BA --BAIXA DO ADIANTAMENTO 
      ,PCCONTA 
      ,PCCONSUM 
 WHERE A.RECNUMADIANTAMENTO = LA.RECNUM 
   and PCCONTA.GRUPOCONTA IN ('401','402','403','404','405','406','501')
   AND A.RECNUMPAGTO = BA.RECNUM 
   AND A.DTESTORNO IS NULL 
   AND PCCONTA.CODCONTA = LA.CODCONTA 
 AND   A.DTLANC BETWEEN '01/04/2024' and '30/04/2024' 
   AND ((LA.CODCONTA = PCCONSUM.CODCONTAADIANTFOR) OR 
       (LA.CODCONTA = PCCONSUM.CODCONTAADIANTFOROUTROS)) 
   AND BA.DTPAGTO IS NOT NULL 
   AND BA.DTESTORNOBAIXA IS NULL 
 ) 
GROUP BY RECNUM ,
       CODFILIAL,
       DTVENC,
       DTPAGTO,
       DTPAGTOMES,
       DTPAGTOANO,
       CODCLI,
       CLIENTE,
       CMV,
       CODCONTA,
       CONTA 


