select S.CODFILIAL,S.ESPECIE,S.SERIE,S.NUMNOTA,S.NUMTRANSVENDA,S.DTSAIDA,S.VLTOTAL,S.CODCOB,S.CODUSUR, U.NOME,S.VLTOTGER as DESPESAS_OU_CONTAS_RECEBER,S.DTCANCEL,S.CONDVENDA as TIPO_VENDA,S.CODFUNCLANC,E.NOME
from PCNFSAID S
left join PCUSUARI U on S.CODUSUR = U.CODUSUR
left join PCEMPR E on S.CODFUNCLANC = E.MATRICULA
where S.GERACP = 'S' and S.CONDVENDA = 9;


select CODCLI from PCNFSAID where NUMNOTA =  91948;

