select 
distinct
 PCCLIENT.CLIENTE,
   PCCLIENT.TELCELENT, 
     PCCLIENT.TELCOB
from PCPEDC
join PCCLIENT on PCPEDC.CODCLI = PCCLIENT.CODCLI
where PCPEDC.POSICAO = 'F'
and PCPEDC.DATA >= TRUNC(SYSDATE) - 30
--and PCPEDC.DATA <= TRUNC(SYSDATE)
order by PCCLIENT.CLIENTE;