select 
L.DTLANC as EMISSAO,
L.CODFORNEC,
F.FORNECEDOR,
L.NUMTRANSENT as TRANSACAO,
L.CODCONTA,
C.CONTA as Desc_CONTA,
L.NUMNOTA as NF,
L.RECNUM as LANCTO,
L.DTVENC as VENCIMENTO,
L.VALOR,
L.NFSERVICO      
from PCLANC L
join PCCONTA C on L.CODCONTA = C.CODCONTA 
left join PCFORNEC F on L.CODFORNEC = F.CODFORNEC
where 0=0
and L.CODFORNEC in(:CODFORNEC)
and nvl(L.DTCOMPETENCIA, L.DTLANC) <= :DTREF
and (L.DTPAGTO is null or L.DTPAGTO > :DTREF)
and (L.NFSERVICO = 'S' 
or L.CODCONTA in( '100001', '100002','4010003'))
order by L.CODFORNEC
;