SELECT PCNFENT.NUMNOTA,
       PCNFENT.DTENT,
       NVL(PCNFSAID.NUMCAR,0) NUMCARREGAMENTO,
       PCNFENT.DTSAIDA,
       DECODE(PCNFENT.VLTOTAL,0,PCESTCOM.VLDEVOLUCAO,PCNFENT.VLTOTAL) AS VLTOTAL,
       0 VLTOTAL1,
       PCNFENT.CODDEVOL,
       PCNFENT.OBS,
       PCTABDEV.MOTIVO,
       PCNFENT.NUMTRANSENT,
       PCNFENT.ROTINALANC,
       NVL(PCNFENT.TOTPESO,0) TOTPESO,
        0 TOTPESO1,
       PCNFSAID.CODFILIALNF,
       PCCLIENT.CODCLI,
       PCCLIENT.CLIENTE, 
       PCCLIENT.MUNICENT,
       PCCLIENT.ENDERENT,
       PCCLIENT.TELENT, 
 PCNFENT.CODUSURDEVOL, 
       PCNFENT.CODMOTORISTADEVOL,
       PCEMPR.NOME,
       PCUSUARI.NOME NOMERCA,
       PCUSUARI.CODSUPERVISOR,
       PCSUPERV.NOME SUPERVISOR,
       FUNC.NOME NOMEFUNC,
       PCNFENT.CODFORNEC,
       PCFORNEC.FORNECEDOR,
       0 QTAVARIA,
       0 VLAVARIA,
       PCNFENT.VLFRETE,
       PCNFENT.VLOUTRAS, 
  ( SELECT SUM (decode(PCMOV.Tipoitem,'C',0, ((DECODE(NVL(PCMOV.QT,0),0,NVL(PCMOV.QTCONT,0),NVL(PCMOV.QT,0))) * 
  ( DECODE(NVL(PCMOV.PUNIT,0),0,NVL(PCMOV.PUNITCONT,0),NVL(PCMOV.PUNIT,0)) + NVL(PCMOV.VLOUTROS,0) + NVL(PCMOV.VLFRETE,0))))) AS VALORDEV 
       FROM   PCMOV, PCPRODUT
       WHERE  PCMOV.CODPROD = PCPRODUT.CODPROD
       AND    PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
       AND    PCMOV.CODOPER IN ('ED','EN')
       AND    PCMOV.DTCANCEL IS NULL ) VLPORFORNEC 
 FROM PCNFENT, PCESTCOM, PCTABDEV, PCCLIENT
,PCEMPR, PCUSUARI, PCSUPERV, PCEMPR FUNC, PCFORNEC, PCNFSAID,PCMOV M
WHERE  ( PCNFENT.CODDEVOL          = PCTABDEV.CODDEVOL(+) ) 
AND PCNFENT.NUMTRANSENT = PCESTCOM.NUMTRANSENT(+) 
AND PCNFENT.NUMNOTA = M.NUMNOTA 
AND PCNFENT.DTENT = M.DTMOV 
AND PCESTCOM.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA(+) 
AND PCNFENT.codfornec = PCFORNEC.codfornec(+) 
AND   ( PCNFENT.CODFORNEC         = PCCLIENT.CODCLI(+) ) 
AND   ( PCNFENT.CODFUNCLANC       = FUNC.MATRICULA(+)) 
AND   ( PCNFENT.CODMOTORISTADEVOL = PCEMPR.MATRICULA(+))
AND   ( PCNFENT.CODUSURDEVOL = PCUSUARI.CODUSUR) 
AND   ( PCUSUARI.CODSUPERVISOR    = PCSUPERV.CODSUPERVISOR(+)) 
AND   ( TO_CHAR(PCNFENT.DTENT , 'YYYY') = TO_CHAR(SYSDATE, 'YYYY') ) 
  AND NVl(PCNFSAID.CONDVENDA,0) NOT IN (4, 8, 10, 13, 20, 98, 99)
AND   ( PCNFENT.TIPODESCARGA IN ('6','7','T') ) 
AND   ( NVL(PCNFENT.OBS, 'X') <> 'NF CANCELADA') 
AND   ( PCNFENT.CODFISCAL IN ('131','132','231','232','199','299') ) 
AND EXISTS (SELECT PCPRODUT.CODPROD FROM PCPRODUT, PCMOV
             WHERE PCMOV.CODPROD = PCPRODUT.CODPROD
             AND PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
             AND PCMOV.NUMNOTA = PCNFENT.NUMNOTA
AND   ( TO_CHAR(PCNFENT.DTENT , 'YYYY') = TO_CHAR(SYSDATE, 'YYYY') ) 
           AND PCMOV.CODFILIAL = PCNFENT.CODFILIAL)
 AND PCNFENT.CODUSURDEVOL = :CODUSUR
   AND PCNFENT.CODDEVOL IN (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,47,52)
 GROUP BY pcnfent.numnota,PCNFENT.DTENT,NVL(PCNFSAID.NUMCAR,0),PCNFENT.DTSAIDA,PCNFENT.CODDEVOL, 
  PCNFENT.CODUSURDEVOL,
 PCNFENT.OBS,PCTABDEV.MOTIVO,PCNFENT.NUMTRANSENT,PCNFENT.ROTINALANC,NVL(PCNFENT.TOTPESO,0),
 PCNFSAID.CODFILIALNF,PCCLIENT.CODCLI,PCCLIENT.CLIENTE, PCCLIENT.MUNICENT,PCCLIENT.ENDERENT,
 PCCLIENT.TELENT, PCNFENT.CODMOTORISTADEVOL, 
 PCEMPR.NOME,PCUSUARI.NOME ,PCUSUARI.CODSUPERVISOR,PCSUPERV.NOME ,FUNC.NOME , 
 PCNFENT.CODFORNEC,PCFORNEC.FORNECEDOR,PCNFENT.VLFRETE,PCNFENT.VLOUTRAS,PCNFENT.VLTOTAL,PCESTCOM.VLDEVOLUCAO 
  ORDER BY codusurdevol, PCNFENT.CODFORNEC, PCNFENT.NUMTRANSENT