select L.RECNUM as N_LANCAMENTO,
       A.NUMTRANSVENDADESC as N_TRANSACAO,
       A.NUMNOTADESC as NUMNOTA,
       L.CODCONTA, 
       C.CONTA,
       F.CODCLI,
       F.CLIENTE
       
from PCLANC L
join PCCONTA C on L.CODCONTA = C.CODCONTA
left join PCCLIENT F on L.CODFORNEC = F.CODCLI
left join PCCRECLI A on L.RECNUM = A.NUMLANC
where 0=0
and L.RECNUM ='10246'
;


select CODCONTAB from PCCLIENT WHERE CODCLI = '22852'
;
select * from PCNFSAID where NUMTRANSVENDA ='160662';


select * from PCNFENT where NUMNOTA ='118589';


SELECT * FROM PCCRECLI WHERE CODCLI ='21755';


select * from PCMOV where NUMNOTA ='118589'
;
--


SELECT DISTINCT
    PCLANC.RECNUM,
    PCLANC.DTLANC,
    PCLANC.CODFILIAL,
    NVL(PCLANC.TIPOLANC, 'P') AS TIPOLANC,
    PCLANC.MOEDA,
    PCLANC.CODCONTA,
    (SELECT CONTA FROM PCCONTA WHERE CODCONTA = PCLANC.CODCONTA) AS CONTA,
    PCLANC.HISTORICO,
    PCLANC.HISTORICO2,
    PCLANC.TIPOPARCEIRO,
    PCLANC.CODFORNEC,
    PCRATEIOPADRAOCONTA.CODRATEIOCONTA,
    PCRATEIOPADRAOCONTA.DESCRICAO AS RATEIOCONTA,
    CASE TIPOPARCEIRO
        WHEN 'F' THEN (SELECT fornecedor FROM pcfornec WHERE CODFORNEC = PCLANC.CODFORNEC)
        WHEN 'C' THEN (SELECT CLIENTE FROM PCCLIENT WHERE CODCLI = PCLANC.CODFORNEC)
        WHEN 'R' THEN (SELECT NOME FROM PCUSUARI WHERE CODUSUR = PCLANC.CODFORNEC)
        WHEN 'M' THEN (SELECT NOME FROM PCempr WHERE MATRICULA = PCLANC.CODFORNEC)
        WHEN 'L' THEN (SELECT NOME FROM PCempr WHERE MATRICULA = PCLANC.CODFORNEC)
        WHEN 'O' THEN (NVL(FORNECEDOR, 'Outros Fornecedores'))
    END AS PARCEIRO,
    PCLANC.NUMNOTA,
    NVL(PCLANC.DUPLIC, 1) AS DUPLIC,
    PCLANC.DTVENC,
    PCLANC.VALOR,
    PCLANC.NUMCODBARRA,
    PCLANC.NUMNOTADEV,
    PCLANC.VALORDEV,
    PCLANC.DESCONTOFIN,
    PCLANC.TXPERM,
    PCLANC.PRORROG,
    PCLANC.DTEMISSAO,
    PCLANC.LOCALIZACAO,
    PCLANC.NOMEFUNC,
    PCLANC.DTPAGTO,
    PCLANC.VPAGO,
    NVL(PCLANC.VPAGOBORDERO, PCLANC.VPAGO) AS VPAGOBORDERO,
    PCLANC.NUMSEQBORDERO,
    PCLANC.DTBORDER,
    PCLANC.NUMBANCO,
    PCLANC.NUMCHEQUE,
    PCLANC.DTCHEQ,
    PCLANC.NUMBORDERO,
    PCLANC.NUMTRANSADIANTFOR,
    PCLANC.NUMTRANSENT,
    PCLANC.NUMTRANS,
    PCLANC.CODFUNCBAIXA,
    CODROTINABAIXA,
    PCLANC.DTMOEDA,
    PCLANC.CODFUNCRECLASSIFIC,
    (SELECT NOME FROM PCEMPR WHERE MATRICULA = PCLANC.CODFUNCRECLASSIFIC) AS cNOMEFUNCRECLASSIF,
    PCLANC.DTRECLASSIFIC,
    PCLANC.CODFUNCULTALTER,
    PCLANC.DTULTALTER,
    PCLANC.INDICE,
    NVL(PCLANC.BOLETO, 'N') AS BOLETO,
    PCLANC.NUMNEGOCIACAO,
    NVL(PCLANC.DTCOMPETENCIA, PCLANC.DTLANC) AS DTCOMPETENCIA,
    NVL(PCLANC.NFSERVICO, 'N') AS NFSERVICO,
    PCLANC.DTAUTOR,
    PCLANC.CODFUNCAUTOR,
    PCLANC.FUNCBLOQ,
    PCLANC.OBSBLOQ,
    PCLANC.DTBLOQ,
    PCLANC.COTACAO,
    PCLANC.CODPROJETO,
    PCLANC.DTCOTACAO,
    PCLANC.MOEDAESTRANGEIRA,
    NVL(PCLANC.CODRECEITA, 0) AS CODRECEITA,
    (SELECT DESCRICAO FROM PCCODIGOSRECEITAFEDERALDARF WHERE CODIGO = NVL(PCLANC.CODRECEITA, 0)) AS DESCRICAORECEITA,
    PCLANC.FORMAPGTO,
    PCLANC.FROTA_CODVEICULO,
    PCLANC.VRECEITABRUTA,
    PCLANC.PERCRECEITABRUTA,
    PCLANC.VLISS,
    PCLANC.VLPIS,
    PCLANC.VLCOFINS,
    PCLANC.VLCSRF,
    PCLANC.VLIRRF,
    PCLANC.VLINSS,
    (SELECT PCMOVCR.DTCOMPENSACAO FROM PCMOVCR WHERE PCLANC.NUMTRANS = PCMOVCR.NUMTRANS AND PCMOVCR.DTESTORNO IS NULL AND ROWNUM = 1) AS DTCOMPENSACAO,
    PCLANC.NUMPARCELAMENTO,
    NVL(PCLANC.PARCELA, 1) AS PARCELA,
    PCLANC.NUMSEQPARCELAMENTO,
    PCLANC.FORNECEDOR,
    NVL(PCLANC.VLVARIACAOCAMBIAL, 0) AS VLVARIACAOCAMBIAL,
    0 AS VALORLIQPAGAR,
    CODROTINACAD,
    IDCONTROLEEMBARQUE,
    CODSERVICOSPEDEFD,
    NVL(PCLANC.ADIANTAMENTO, 'N') AS ADIANTAMENTO,
    PCLANC.TIPOSERVICO,
    PCLANC.LACREDIGCONECSOCIAL,
    PCLANC.IDENTIFICADORFGTS,
    PCLANC.OPCAOPAGAMENTOIPVA,
    PCLANC.CODFUNCAUTSUPLORC,
    PCLANC.DATAAUTSUPLORC,
    PCLANC.NUMPRESTACAOCONTA,
    PCLANC.NUMADIANTAMENTO,
    PCLANC.NUMSEQCONTRATOEMPRESTIMO,
    (SELECT NUMCONTRATO FROM PCCONTRATOEMPRESTIMO E WHERE E.NUMSEQCONTRATOEMPRESTIMO = PCLANC.NUMSEQCONTRATOEMPRESTIMO) AS NUMCONTRATO,
    PCCONTA.TIPO,
    PCLANC.DTESTORNOBAIXA,
    (SELECT PCCOTACAOMOEDAC.MOEDA FROM PCCOTACAOMOEDAC WHERE PCCOTACAOMOEDAC.CODIGO = PCLANC.MOEDAESTRANGEIRA) AS NOMEMOEDAESTRANGEIRA,
    PCPROJETO.PROJETO,
    PCVEICUL.DESCRICAO AS VEICULO,
    (SELECT PCHIST.CODHIST FROM PCHIST WHERE PCHIST.HISTORICO = PCLANC.HISTORICO AND ROWNUM = 1) AS CODHIST,
    PCLANC.VALORMOEDAESTRANGEIRA,
    PCLANC.DTCOTACAOBAIXA,
    PCLANC.COTACAOBAIXA,
    PCLANC.RECNUMPRINC,
    NVL(PCLANC.VLRUTILIZADOADIANTFORNEC, 0) AS VLRUTILIZADOADIANTFORNEC,
    PCLANC.CODSERVICOSPEDIRPF,
    PCLANC.CODSERVICOSPEDIRPJ,
    PCLANC.CODSERVICOSPEDBNI,
    PCLANC.REINFEVENTOR4040
FROM PCLANC, PCCONTA, PCRATEIOPADRAOCONTA, PCRATEIOCONTAS, PCPROJETO, PCVEICUL
WHERE PCLANC.CODCONTA = PCCONTA.CODCONTA
    AND PCLANC.CODFILIAL IN (DECODE((SELECT COUNT(*) FROM PCLIB WHERE CODFUNC = 16 AND CODTABELA = 1 AND CODIGOA = '99'), 0, (SELECT CODIGOA FROM PCLIB WHERE CODTABELA = 1 AND CODFUNC = 16 AND CODIGOA = PCLANC.CODFILIAL), PCLANC.CODFILIAL))
    AND PCLANC.RECNUM = PCRATEIOCONTAS.RECNUM(+)
    AND PCRATEIOCONTAS.CODRATEIOCONTA = PCRATEIOPADRAOCONTA.CODRATEIOCONTA(+)
    AND PCLANC.DTLANC BETWEEN '13/09/2023' AND '13/09/2023'
    AND PCCONTA.GRUPOCONTA IN (
        SELECT DISTINCT (PCGRUPO.CODGRUPO)
        FROM PCGRUPO, PCLIB
        WHERE (((PCGRUPO.CODGRUPO <> 9999) AND EXISTS (SELECT L.CODIGON FROM PCLIB L WHERE L.CODTABELA = PCLIB.CODTABELA AND L.CODFUNC = PCLIB.CODFUNC AND L.CODIGON = 9999)) OR ((PCGRUPO.CODGRUPO IN (SELECT L.CODIGON FROM PCLIB L WHERE L.CODTABELA = 6 AND L.CODFUNC = PCLIB.CODFUNC)) AND NOT EXISTS (SELECT L.CODIGON FROM PCLIB L WHERE L.CODTABELA = PCLIB.CODTABELA AND L.CODFUNC = PCLIB.CODFUNC AND L.CODIGON = 9999)))
        AND PCLIB.CODTABELA = 6
        AND PCLIB.CODFUNC = 16
    )
    AND (
        ((TIPOPARCEIRO = 'F') AND (EXISTS (SELECT L.CODIGON FROM PCLIB L WHERE L.CODTABELA = 3 AND L.CODFUNC = 16 AND ((L.CODIGON = PCLANC.CODFORNEC) OR (L.CODIGON = '999999')))))
        OR (TIPOPARCEIRO <> 'F')
    )
    AND PCLANC.CODFILIAL = '2'
    AND NOT ((PCLANC.VPAGO = 0) AND (PCLANC.DTESTORNOBAIXA IS NOT NULL))
    AND PCLANC.CODPROJETO = PCPROJETO.CODPROJETO(+)
    AND PCLANC.FROTA_CODVEICULO = PCVEICUL.CODVEICULO(+)
ORDER BY RECNUM;


