select * from PCNFENT
where NUMNOTA='7'
and SERIE='3';

select VLPIS,
       VLCOFINS,
       VLOUTRAS,
       VLIPI,
       VLTOTAL
from PCNFENT
where NUMNOTA='7'
and SERIE = '3'; 

SELECT PCMOV.NUMNOTA,sum(PCMOV.VLIMPORTACAO * PCMOV.QTCONT) + PCNFENT.VLOUTRAS  as VLOUTRASDESP  
FROM PCMOV
join PCNFENT on PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
WHEre PCMOV.NUMTRANSENT='12855'
and PCNFENT.SERIE='3'
group by PCMOV.NUMNOTA, PCNFENT.VLOUTRAS;

SELECT * FROM PCLOGALTERACAODADOS;


select coalesce(SUM(PCMOV.VLIMPORTACAO * PCMOV.QTCONT) + PCNFENT.VLOUTRAS, PCNFENT.VLOUTRAS) as VLOUTRASDESP
FROM PCMOV
JOIN PCNFENT ON PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
WHERE PCNFENT.NUMTRANSENT='12855' 
GROUP BY PCNFENT.VLOUTRAS;


select SUM(nvl(PCMOV.VLIMPORTACAO, 0) * nvl(PCMOV.QTCONT, 0)) + nvl(PCNFENT.VLOUTRAS, 0) as VLOUTRASDESP
from PCMOV
join PCNFENT on PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
where PCNFENT.NUMTRANSENT = '168498'
group by PCNFENT.VLOUTRAS;



select coalesce(sum(nvl(PCMOV.VLIMPORTACAO, 0) * PCMOV.QTCONT) + nvl(PCNFENT.VLOUTRAS, 0) + nvl(PCNFSAID.VLOUTRASDESP, 0), 0) as VLOUTRASDESP
from PCMOV
left join PCNFENT on PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
left join PCNFSAID on PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
where
PCNFENT.NUMTRANSENT = '12855'
or
PCNFSAID.NUMTRANSVENDA = '12855'
group by PCNFENT.VLOUTRAS, PCNFSAID.VLOUTRASDESP;



select coalesce(sum(nvl(PCMOV.VLIMPORTACAO, 0) * PCMOV.QTCONT), 0)  as IMPimportacao
from PCMOV
left join PCNFENT on PCMOV.NUMTRANSENT = PCNFENT.NUMTRANSENT
left join PCNFSAID on PCMOV.NUMTRANSVENDA = PCNFSAID.NUMTRANSVENDA
where PCNFENT.NUMTRANSENT = '12855' or PCNFSAID.NUMTRANSVENDA = '12855';






  