SELECT DISTINCT 
       PCCONTA.CODCONTA,
       PCCONTA.CONTA,
       PCCONTA.GRUPOCONTA,
       PCGRUPO.GRUPO 
FROM PCCONTA,
     PCGRUPO,
     PCLIB
WHERE 0=0 
AND PCCONTA.CODCONTA<>(SELECT NVL(CODCONTFOR,0) FROM PCCONSUM ) 
AND PCCONTA.CODCONTA<>(SELECT NVL(CODCONTFRE,0) FROM PCCONSUM ) 
AND PCCONTA.CODCONTA<>(SELECT NVL(CODCONTOUT,0) FROM PCCONSUM ) 
AND PCCONTA.CODCONTA<>(SELECT NVL(CODCONTAADIANTFOR,0) FROM PCCONSUM ) 
AND PCCONTA.CODCONTA<>(SELECT NVL(CODCONTAADIANTFOROUTROS,0) FROM PCCONSUM ) 
AND PCCONTA.CODCONTA<>(SELECT NVL(CODCONTAJUSTEEST,0) FROM PCCONSUM ) 
AND PCCONTA.GRUPOCONTA=PCGRUPO.CODGRUPO 
AND PCGRUPO.CODGRUPO >= 100 
AND PCCONTA.TIPO<>'I'
AND ((PCCONTA.CODCONTA NOT IN (SELECT NVL(CODCONTANTPAG,0) FROM PCCONSUM))
AND (PCCONTA.CODCONTA NOT IN  (SELECT NVL(CODCONTRECJUR,0) FROM PCCONSUM))
AND (PCCONTA.CODCONTA NOT IN  (SELECT NVL(CODCONTPAGJUR,0) FROM PCCONSUM)))
AND PCCONTA.GRUPOCONTA=PCLIB.CODIGON 
AND PCLIB.CODTABELA = '6' 
AND PCLIB.CODFUNC= '16' 
AND PCCONTA.CODCONTA NOT IN (SELECT NVL(P.VALOR, 0) FROM PCPARAMFILIAL P WHERE P.NOME = 'CODCONTAADIANTFUNC')
AND (SELECT COUNT(*) FROM PCPARAMFILIAL WHERE NOME = 'CODCONTAADIANTFUNC' 
AND VALOR = PCCONTA.CODCONTA) <= 0
AND PCCONTA.CODCONTA = '100002'  
ORDER BY PCCONTA.CODCONTA 