select
    PCPEDI.PVENDA as VENDAFAT,
    nvl(PCTABPR.PVENDA, 0) as PVENDA,
    to_char(SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0))), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as vl_CMV,
    to_char(((PCPEDI.PVENDA - SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0)))) / PCPEDI.PVENDA * 100), 'FM999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' as MARGEM,
    sum(PCPEDI.PVENDA),
    sum(PCPEDI.PVENDA) over () as TOTAL_PVENDA,
    SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0))) over () as TOTAL_cmv,
    to_char((((sum(PCPEDI.PVENDA) over () - SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0))) over ()) / sum(PCPEDI.PVENDA) over ())* 100),'9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TESTE
from
    PCPRODUT,
    PCEST,
    PCPRODFILIAL,
    PCDEPTO,
    PCFORNEC,
    PCTABPR,
    PCTRIBUT,
    PCFILIAL,
    PCCONSUM,
    PCREGIAO,
    PCCOTACAOMOEDAI,
    PCTABTRIB,
    PCPEDC,
    PCPEDI
where
    PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
    and PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
    and PCEST.DTULTENT = PCCOTACAOMOEDAI.DATACOTACAO(+)
    --and PCCOTACAOMOEDAI.CODIGO(+) = :CODMOEDA
    and PCPRODUT.CODPROD = PCEST.CODPROD
    and PCPRODUT.CODPROD = PCTABPR.CODPROD
    -- and PCTABPR.NUMREGIAO = DECODE(nvl(2,-1),-1, nvl(PCFILIAL.NUMREGIAOPADRAO, PCCONSUM.NUMREGIAOPADRAO), 2)
    and PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO
    and PCEST.CODFILIAL = PCPRODFILIAL.CODFILIAL
    and PCEST.CODPROD = PCPRODFILIAL.CODPROD
    and PCEST.CODFILIAL = PCPEDC.CODFILIAL
    and PCFILIAL.CODIGO = PCEST.CODFILIAL
    and PCPRODUT.CODPROD = PCPEDI.CODPROD
    and PCTABTRIB.CODFILIALNF = DECODE(nvl(PCREGIAO.CODFILIAL, '99'), '99', PCEST.CODFILIAL, PCREGIAO.CODFILIAL)
    and PCTABTRIB.UFDESTINO = PCREGIAO.UF
    and PCTABTRIB.CODPROD = PCTABPR.CODPROD
    and PCTABTRIB.CODST = PCTRIBUT.CODST
  --  and PCPEDC.NUMPED = '1032000755'
    and PCPEDC.CODUSUR = '1062'
    and PCPEDC.DATA between '01/07/2023' and '17/07/2023'
    and PCPEDI.NUMPED = PCPEDC.NUMPED
    -- and PCPEDI.CODPROD = '893'
    and PCTABPR.NUMREGIAO = PCPEDC.NUMREGIAO
group by
    PCTABPR.PVENDA,
    PCPEDI.PVENDA,
    PCEST.CUSTOULTENT,
    PCTRIBUT.PERDESCCUSTO,
    PCREGIAO.VLFRETEKG,
    PCPRODUT.PCOMREP1,
    PCTRIBUT.CODICMTAB
order by
    PCPEDI.PVENDA
    fetch first 1 rows only;
    
    --------------------------


select
   PCPEDI.CODPROD,
    PCREGIAO.NUMREGIAO,
    PCPEDI.PVENDA as VENDAFAT,
    nvl(PCTABPR.PVENDA, 0) as PVENDA,
    nvl(PCEST.CUSTOULTENT, 0) as VLULTENT,
    nvl(PCTRIBUT.PERDESCCUSTO, 0) as DESCCUST,
    to_char(SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0))), '9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') as vl_CMV,
    to_char(((PCPEDI.PVENDA - SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0)))) / PCPEDI.PVENDA * 100), 'FM999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') || '%' as MARGEM,
    sum(PCPEDI.PVENDA),
    to_char(sum(PCPEDI.PVENDA)over (), 'FM999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')  as TOTAL_PVENDA,
    to_char(SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0)))over (), 'FM999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''')  as TOTAL_cmv,
    to_char((((sum(PCPEDI.PVENDA) over () - SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0))) over ()) / sum(PCPEDI.PVENDA) over ())* 100),'9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TESTE
from
    PCPRODUT,
    PCEST,
    PCPRODFILIAL,
    PCDEPTO,
    PCFORNEC,
    PCTABPR,
    PCTRIBUT,
    PCFILIAL,
    PCCONSUM,
    PCREGIAO,
    PCCOTACAOMOEDAI,
    PCTABTRIB,
    PCPEDC,
    PCPEDI
where
    PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
    and PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
    and PCEST.DTULTENT = PCCOTACAOMOEDAI.DATACOTACAO(+)
    --and PCCOTACAOMOEDAI.CODIGO(+) = :CODMOEDA
    and PCPRODUT.CODPROD = PCEST.CODPROD
    and PCPRODUT.CODPROD = PCTABPR.CODPROD
    -- and PCTABPR.NUMREGIAO = DECODE(nvl(2,-1),-1, nvl(PCFILIAL.NUMREGIAOPADRAO, PCCONSUM.NUMREGIAOPADRAO), 2)
    and PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO
    and PCEST.CODFILIAL = PCPRODFILIAL.CODFILIAL
    and PCEST.CODPROD = PCPRODFILIAL.CODPROD
    and PCEST.CODFILIAL = PCPEDC.CODFILIAL
    and PCFILIAL.CODIGO = PCEST.CODFILIAL
    and PCPRODUT.CODPROD = PCPEDI.CODPROD
    and PCTABTRIB.CODFILIALNF = DECODE(nvl(PCREGIAO.CODFILIAL, '99'), '99', PCEST.CODFILIAL, PCREGIAO.CODFILIAL)
    and PCTABTRIB.UFDESTINO = PCREGIAO.UF
    and PCTABTRIB.CODPROD = PCTABPR.CODPROD
    and PCTABTRIB.CODST = PCTRIBUT.CODST
  --  and PCPEDC.NUMPED = '1032000755'
    and PCPEDC.CODUSUR = '1062'
    and PCPEDC.DATA between '01/07/2023' and '17/07/2023'
    and PCPEDI.NUMPED = PCPEDC.NUMPED
    -- and PCPEDI.CODPROD = '893'
    and PCTABPR.NUMREGIAO = PCPEDC.NUMREGIAO
group by
    PCTABPR.PVENDA,
    PCPEDI.PVENDA,
    PCEST.CUSTOULTENT,
    PCTRIBUT.PERDESCCUSTO,
    PCREGIAO.VLFRETEKG,
    PCPRODUT.PCOMREP1,
    PCTRIBUT.CODICMTAB,
    PCPEDI.CODPROD,
    PCREGIAO.NUMREGIAO
order by
    PCPEDI.PVENDA
    fetch first 1 rows only;


--FINALMENTEEEEEEEEEEEEEEEEAAAAAAAAAAA

select
    to_char((((sum(PCPEDI.PVENDA) over () - SUM(nvl(PCEST.CUSTOULTENT, 0) - nvl(PCTRIBUT.PERDESCCUSTO, 0) + nvl(PCREGIAO.VLFRETEKG, 0) + (nvl(PCTABPR.PVENDA * nvl(PCPRODUT.PCOMREP1, 0) / 100, 0)) + (nvl(PCTABPR.PVENDA * nvl(PCTRIBUT.CODICMTAB, 0) / 100, 0))) over ()) / sum(PCPEDI.PVENDA) over ())* 100),'9G999G999G999D99', 'NLS_NUMERIC_CHARACTERS = '',.''') AS TESTE
from
    PCPRODUT,
    PCEST,
    PCPRODFILIAL,
    PCDEPTO,
    PCFORNEC,
    PCTABPR,
    PCTRIBUT,
    PCFILIAL,
    PCCONSUM,
    PCREGIAO,
    PCCOTACAOMOEDAI,
    PCTABTRIB,
    PCPEDC,
    PCPEDI,
    PCMOV
where
    PCPRODUT.CODEPTO = PCDEPTO.CODEPTO
    and PCPRODUT.CODFORNEC = PCFORNEC.CODFORNEC
    and PCEST.DTULTENT = PCCOTACAOMOEDAI.DATACOTACAO(+)
    --and PCCOTACAOMOEDAI.CODIGO(+) = :CODMOEDA
    and PCPRODUT.CODPROD = PCEST.CODPROD
    and PCPRODUT.CODPROD = PCTABPR.CODPROD
    -- and PCTABPR.NUMREGIAO = DECODE(nvl(2,-1),-1, nvl(PCFILIAL.NUMREGIAOPADRAO, PCCONSUM.NUMREGIAOPADRAO), 2)
    and PCTABPR.NUMREGIAO = PCREGIAO.NUMREGIAO
    and PCEST.CODFILIAL = PCPRODFILIAL.CODFILIAL
    and PCEST.CODPROD = PCPRODFILIAL.CODPROD
    and PCEST.CODFILIAL = PCPEDC.CODFILIAL
    and PCFILIAL.CODIGO = PCEST.CODFILIAL
    and PCPRODUT.CODPROD = PCPEDI.CODPROD
    and PCTABTRIB.CODFILIALNF in ('2','3','4')
    and PCTABTRIB.UFDESTINO = PCREGIAO.UF
    and PCTABTRIB.CODPROD = PCTABPR.CODPROD
    and PCTABTRIB.CODST = PCTRIBUT.CODST
   -- and PCPEDC.NUMPED = '1062000513'
    and PCMOV.QT = PCPEDI.QT
    and PCMOV.PUNIT = PCPEDI.PVENDA
    and PCPEDC.CODUSUR in '1011'
    and PCPEDC.DATA between '01/07/2023' and '17/07/2023'
    and PCPEDI.NUMPED = PCPEDC.NUMPED
    -- and PCPEDI.CODPROD = '893'
    and PCTABPR.NUMREGIAO = PCPEDC.NUMREGIAO
group by
    PCTABPR.PVENDA,
    PCPEDI.PVENDA,
    PCEST.CUSTOULTENT,
    PCTRIBUT.PERDESCCUSTO,
    PCREGIAO.VLFRETEKG,
    PCPRODUT.PCOMREP1,
    PCTRIBUT.CODICMTAB,
    PCPEDI.CODPROD,
    PCREGIAO.NUMREGIAO,
    PCMOV.QT,
    PCMOV.PUNIT,
    PCPEDC.NUMPED
order by
    PCPEDI.PVENDA
    fetch first 1 rows only;
