WITH CalculatedFields AS (
    SELECT 
    cast(CLI.FANTASIA as varchar(120)) AS FANTASIA,
    cast(cli.cliente  as varchar(120)) as nomecli,
    PED.OBS1,
    PED.OBS2,
    R.REGIAO,
    S.CODFILIAL,
    S.NUMNOTA,
    U.NOMECONTATO,
    U.CODCONTATO,
    U.CARGO AS CODUSUR2,
    S.numtransvenda,
    S.VLTOTAL - S.VLFRETE AS vlvenda_itens,
    S.VLTABELA - S.VLFRETE as vltabela_ITENS,
    s.CODCLI,
    P.CODUSUR2 AS USUR2_ATUAL,
    P.DTPAG,
    P.DTESTORNO,
    P.DTPAGCOMISSAO,
    P.DTPAGCOMISSAO2,
    P.DTPAGCOMISSAO3,
    P.DTPAGCOMISSAO4,
    p.dtvenc,
    s.dtsaida,
    P.DUPLIC,
    P.PREST,
    P.CODCOB,
    p.CODCOBORIG,
    COB.COBRANCA,
    p.VALOR,
    P.VALORORIG,
    P.VPAGO,
    S.VLFRETE,
    S.VLTOTAL,
    S.VLTABELA,
    P.NUMTRANSENTDEVCLI,
    CASE WHEN VALOR < 0 THEN P.OBSFINANC 
    ELSE '' END AS OBSFINANC,
    CASE WHEN P.NUMTRANSENTDEVCLI IS NOT NULL THEN
        (SELECT SUM(PUNITCONT*QTCONT) FROM PCMOV WHERE NUMTRANSENT = P.NUMTRANSENTDEVCLI)
        WHEN S.DTDEVOL IS NOT NULL THEN S.VLDEVOLUCAO
    END AS VLDEVOLVIDO,
    P.DTDEVOL AS DTDEVOLPARCIAL,
    trunc( ( (P.VALORORIG/(s.vltotal)) * (S.vltabela) * ((USUR.PERCENT2)/100)) / P.VALORORIG,5)*100  AS percom,
    USUR.PERCENT2 AS COM_VENDEDOR,
    USUR.CODUSUR AS CODVENDEDOR,
    USUR.NOME AS VENDEDOR,
    CASE 
        WHEN P.DTPAGCOMISSAO IS NULL THEN 
      TRUNC(( (P.VALORORIG/(s.vltotal)) * (S.vltabela) * ((USUR.PERCENT2)/100)) , 2)
    ELSE 
        0
    END AS COMISSAO_VENDEDOR,
    
    CASE 
        WHEN (P.CODCOB IN ('DEVP','DEVT')) THEN '4-DEVOLUÇÕES'
        WHEN P.VPAGO IS NOT NULL AND P.DTPAG IS NOT NULL THEN '1-FATURAS QUITADAS'
        WHEN P.VPAGO IS NULL AND P.DTPAG IS NULL AND P.DTVENC < SYSDATE THEN '3-FATURAS VENCIDAS (CLIENTES EM ABERTO)'
        WHEN P.VPAGO IS NULL AND P.DTPAG IS NULL AND P.DTVENC >= SYSDATE THEN '2-FATURAS A VENCER'
    END AS STATUS,
    
    CASE WHEN P.COMA_STATUSAPRV = 'C' THEN 'PAGO COM CREDITO'
         WHEN P.COMA_STATUSAPRV = 'D' THEN 'PAGO COM NFE'
         WHEN P.COMA_STATUSAPRV = 'E' THEN 'PAGO SEM NFE'
         WHEN P.COMA_STATUSAPRV = 'A' THEN 'APROVADA PENDENTE PG'
         WHEN P.COMA_STATUSAPRV = 'R' THEN 'REPROVADA'
         WHEN P.COMA_STATUSAPRV IS NULL THEN 'PENDENTE APROVAÇÃO'
    ELSE 'DESCONHECIDO'
    END AS STATUSAPRV,
    
    CASE WHEN (P.CODUSUR2 IS NULL or P.CODUSUR2 = 0) AND P.PERCOM2 =0 THEN 'PENDENTE'
    ELSE 'APROVADO'
    END AS APROVACAO,
    
    CASE WHEN R.REGIAO LIKE '%CF%' AND (P.PERCOM2 = 0 OR P.PERCOM2 IS NULL)  THEN 
   TRUNC((P.VALORORIG/s.vltotal) * ( S.vltotal - 
        ( SELECT 
            SUM(PI.QT*PR.PVENDA)
          FROM
            PCPEDI PI,
            PCTABPR PR
          WHERE 
            PI.NUMPED = PED.NUMPED
            AND PR.NUMREGIAO = PED.NUMREGIAO+1
            AND PI.CODPROD = PR.CODPROD
        ) ),2)
        
    WHEN P.PERCOM2 > 0 THEN TRUNC( (P.PERCOM2/100)*P.VALOR,2 ) 
    
    ELSE 0 END AS COMISSAO_AGENCIADOR,
    
    
     CASE 
     WHEN R.REGIAO LIKE '%CF%' AND (P.PERCOM2 = 0 OR P.PERCOM2 IS NULL) THEN 
       TRUNC(( S.vltotal - 
            ( SELECT 
                SUM(PI.QT*PR.PVENDA)
              FROM
                PCPEDI PI,
                PCTABPR PR
              WHERE 
                PI.NUMPED = PED.NUMPED
                AND PR.NUMREGIAO = PED.NUMREGIAO+1
                AND PI.CODPROD = PR.CODPROD
            ) ) / s.vltotal,5)*100
        
        WHEN P.PERCOM2 > 0 THEN P.PERCOM2      
        ELSE 0 END AS PERCOM2,
    
    CASE  
    WHEN PED.COMA_VLTABPSD IS NOT NULL THEN PED.COMA_VLTABPSD
    WHEN R.REGIAO LIKE '%CF%' THEN  
        ( SELECT 
            SUM(PI.QT*PR.PVENDA)
          FROM
            PCPEDI PI,
            PCTABPR PR
          WHERE 
            PI.NUMPED = PED.NUMPED
            AND PR.NUMREGIAO = PED.NUMREGIAO+1
            AND PI.CODPROD = PR.CODPROD)
                
    ELSE 0 END AS VL45REGIAO2,
    
    P.COMA_DTPAGCOM,
    P.COMA_DTAPROV,
    
    CASE WHEN S.DTDEVOL IS NOT NULL AND S.VLDEVOLUCAO = S.VLTOTAL  AND P.CODCOB = 'CRED' THEN 'DEV TOTAL COM CREDITO'
         WHEN S.DTDEVOL IS NOT NULL AND S.VLDEVOLUCAO = S.VLTOTAL THEN 'DEV TOTAL'
         WHEN S.DTDEVOL IS NOT NULL AND S.VLDEVOLUCAO < S.VLTOTAL THEN 'DEV PARCIAL' 
         WHEN P.DTDEVOL IS NOT NULL AND S.VLDEVOLUCAO < S.VLTOTAL AND P.CODCOB = 'CRED' THEN 'DEV PARCIAL COM CREDITO'
         WHEN P.DTDEVOL IS NOT NULL AND S.VLDEVOLUCAO < S.VLTOTAL THEN 'DEV PARCIAL'
         ELSE 'SEM DEV'
    END AS STATUS_DEV,
    
    CASE WHEN S.DTDEVOL IS NOT NULL THEN S.DTDEVOL
        WHEN S.DTDEVOL IS NULL AND P.DTDEVOL IS NOT NULL THEN P.DTDEVOL
        ELSE NULL
   END AS DTDEVOL

FROM 
    PCCONTATO U 
    INNER JOIN PCPEDC PED ON PED.CODCONTATO = U.CODCONTATO
    inner JOIN PCPREST P ON P.NUMTRANSVENDA = PED.NUMTRANSVENDA 
        AND P.NUMPED = PED.NUMPED 
        AND P.CODCLI = PED.CODCLI
    INNER JOIN PCNFSAID S ON S.NUMTRANSVENDA = PED.NUMTRANSVENDA
    INNER JOIN PCUSUARI USUR ON USUR.CODUSUR = s.CODUSUR
    INNER JOIN PCCLIENT CLI ON CLI.CODCLI = P.CODCLI
    INNER JOIN PCCOB COB ON COB.CODCOB = P.CODCOBORIG
    INNER JOIN PCREGIAO R ON R.NUMREGIAO = PED.NUMREGIAO
    
   
WHERE 
    U.TIPOCONTATO = 'P'
    AND s.DTCANCEL IS NULL
    --AND (S.DTDEVOL IS NULL)
    AND S.CONDVENDA IN (1,7)
    AND S.DTCANCEL IS NULL
    AND P.TIPOESTORNO IS NULL
    AND (CASE WHEN P.CODCOB = 'DEVP' AND P.VPAGO > 0 THEN 'INVALID' 
             WHEN P.CODCOB IN ('CARC','CHDV', 'JUR', 'VALE', 'CANC', 'TR', 'BNF', 'BNFT', 'BNFR', 'BNTR', 'BNRP') THEN 'INVALID'
             WHEN P.CODCOB = 'DESD' AND P.CODCOBORIG IN ('CARV', 'CARD','CARP') AND P.VPAGO = 0 THEN 'VALID'
             WHEN P.CODCOB = 'DESD' AND (SELECT X.CARTAO FROM PCCOB X WHERE X.CODCOB = P.CODCOBORIG ) = 'N' THEN 'INVALID'
         ELSE 'VALID' END) = 'VALID'
Order by
    U.NOMECONTATO, P.DUPLIC, P.PREST, CLI.FANTASIA 
)

SELECT 
    FANTASIA,
    nomecli,
    OBS1,
    OBS2,
    REGIAO,
    CODFILIAL,
    NUMNOTA,
    NOMECONTATO,
    CODCONTATO,
    CODUSUR2,
    numtransvenda,
    vlvenda_itens,
    vltabela_ITENS,
    CODCLI,
    USUR2_ATUAL,
    DTPAG,
    DTESTORNO,
    DTPAGCOMISSAO,
    DTPAGCOMISSAO2,
    DTPAGCOMISSAO3,
    DTPAGCOMISSAO4,
    dtvenc,
    dtsaida,
    DUPLIC,
    PREST,
    CODCOB,
    CODCOBORIG,
    COBRANCA,
    VALOR,
    VALORORIG,
    VPAGO,
    VLFRETE,
    VLTOTAL,
    VLTABELA,
    NUMTRANSENTDEVCLI,
    OBSFINANC,
    VLDEVOLVIDO,
    DTDEVOLPARCIAL,
    percom,
    COM_VENDEDOR,
    CODVENDEDOR,
    VENDEDOR,
    COMISSAO_VENDEDOR,
    CASE 
        WHEN CODFILIAL = 4 THEN ROUND(COMISSAO_AGENCIADOR * 0.85, 2)
        ELSE ROUND(COMISSAO_AGENCIADOR * 0.75, 2)
    END AS COMISSAO_COM_NFE,
    CASE 
        WHEN CODFILIAL = 4 THEN ROUND(COMISSAO_AGENCIADOR * 0.4, 2)
        ELSE ROUND(COMISSAO_AGENCIADOR * 0.4, 2)
    END AS COMISSAO_SEM_NFE,
    CASE 
        WHEN CODFILIAL = 4 THEN ROUND(COMISSAO_AGENCIADOR * 0.9, 2)
        ELSE ROUND(COMISSAO_AGENCIADOR * 0.75, 2)
    END AS COMISSAO_COM_CREDITO,
    STATUS,
    STATUSAPRV,
    APROVACAO
FROM 
    CalculatedFields
ORDER BY
    NOMECONTATO, DUPLIC, PREST, FANTASIA;
