select M.CODFILIAL FILIAL,M.NUMNOTA NOTA,M.DTMOV DTFAT,M.CODPROD, P.DESCRICAO,M.QT QT_VENDIDA, M.CODUSUR RCA,U.NOME, M.CODCLI, C.CLIENTE
from PCMOV M 
join PCPRODUT P on M.CODPROD = P.CODPROD
join PCUSUARI U on M.CODUSUR = U.CODUSUR
left join PCCLIENT C on M.CODCLI = C.CODCLI
join PCNFSAID S on M.NUMNOTA = S.NUMNOTA
where 0=0
and M.DTMOV between '01/09/2023' and '25/09/2023'
and S.DTCANCEL is null
and S.DTDEVOL is null
and M.CODPROD in ('3389','3386')
;


SELECT * FROM PCPEDI WHERE NUMNOTA = 35505